---
title: "Descriptive Statistics for SPLT data"
author: "John Flournoy"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  message = F, error = F,warning = F, cache = T,
  comment = "#>"
)
```

# Sample information

The table below shows the number of participants in each sample. TDS3 has very few participants, and as it was intended to bolster numbers for TDS1, will be collapsed.

```{r load_packages_and_data}
library(probly)
library(dplyr)
library(tidyr)
library(ggplot2)
data('splt', 'splt_confidence', 'splt_dev_and_demog')

sample_labels <- c(
    'TDS1' = 'Foster-care involved adolescents',
    'TDS2' = 'Community adolescents',
    'yads' = 'College students',
    'yads_online' = 'College students - online'
)

condition_labels <- c(
    'HngT' = 'Hungry/Thirsty',
    'DtnL' = 'Dating/Looking', 
    'PplU' = 'Popular/Unpopular'
)

splt$condition <- factor(splt$condition, levels = names(condition_labels), labels = condition_labels)
splt$sample <- factor(splt$sample, levels = names(sample_labels), labels = sample_labels)
splt_dev_and_demog$sample <- factor(splt_dev_and_demog$sample, levels = names(sample_labels), labels = sample_labels)
```

```{r sample_size}
knitr::kable(
    dplyr::select(
        dplyr::mutate(
            dplyr::summarize(
                dplyr::group_by(
                    dplyr::distinct(splt, id, dir, filename, sample),
                    sample),
                n = n())),
        sample, n),
    caption = 'Individuals in each sample',
    col.names = c('Sample', 'N'))
```

```{r summary, results='asis'}
library(tables)
(tables::tabular(
    (Sample=sample) + 1 ~ 
        (N=1) +
        ((Age=age) + (PDSS=PDSS_pdss))*
        (Format(digits=2)*((Mean=(function(x){mean(as.numeric(x), na.rm=T)})) + 
                               (SD=(function(x){sd(x, na.rm=T)}))) + 
             (Missing=(function(x){m <- sum(is.na(x));ifelse(m==0,'.',m)}))), 
    data = splt_dev_and_demog))
```

```{r proportion_trials_per_condition}
splt_by_cond_samp <- dplyr::group_by(splt, condition, sample)
splt_summary_optimal_feedback <- dplyr::summarize(
    splt_by_cond_samp,
    p_optimal_correct = mean((proportion == '20_80') == (correct_r == 1))
)

knitr::kable(splt_summary_optimal_feedback,
             col.names = c('Condition', 'Sample', 'P(Reward | Optimal)'),
             caption = 'Probability that an optimal choice results in reward',
             digits = 3)
```




```{r reaction_time, fig.width=10.5, fig.height=8}
ggplot2::ggplot(
    dplyr::filter(splt, rt > 0),
    ggplot2::aes(x = rt/1000)) + 
    ggplot2::geom_vline(xintercept = 1, size = .5, color = '#666666') + 
    ggplot2::geom_histogram(binwidth = .1, fill = 'black') +
    ggplot2::theme_minimal() + 
    ggplot2::theme(strip.background = element_blank(), 
                   strip.text = element_blank()) + 
    ggplot2::scale_x_continuous(breaks = c(0, 1, 2)) +
    facet_wrap(~id, ncol = 20) + 
    coord_cartesian(x = c(0, 2)) +
    labs(x = 'Trial reaction-time (s)', 
         y = 'Count',
         title = 'Reaction time for all participants')

max_number_of_trials <- max(
    dplyr::summarise(
        dplyr::group_by(
            dplyr::filter(splt, !is.na(pressed_r)), 
            id, condition),
        n_trials = n())$n_trials
    )

ggplot2::ggplot(
    dplyr::filter(splt, !is.na(pressed_r)),
    ggplot2::aes(x = condition)) + 
    ggplot2::geom_hline(yintercept = max_number_of_trials, color = '#666666') + 
    ggplot2::geom_bar(fill = '#bbbbbb') +
    ggplot2::theme_minimal() + 
    ggplot2::theme(strip.background = element_blank(),
                   strip.text = element_blank(),
                   axis.text.x = element_text(angle = 360-45, hjust = 0)) +
    facet_wrap(~id, ncol = 20) + 
    labs(x = 'Condition', 
         y = paste0('Number of trials (line at max = ', max_number_of_trials, ')'),
         title = 'Trials per condition for all participants')
```

# Raw task data

Averaging over trials

```{r fig.width=7, fig.height=6}

splt_averages <- splt %>%
    dplyr::group_by(sample, condition, condition_trial_index) %>%
    dplyr::summarize(p_optimal = mean(correcttrue, na.rm = T)) %>%
    dplyr::ungroup()
    
splt_averages_over_samples <- splt %>%
    dplyr::group_by(condition, condition_trial_index) %>%
    dplyr::summarize(p_optimal = mean(correcttrue, na.rm = T)) %>%
    dplyr::ungroup()

ggplot2::ggplot(
    splt_averages,
    ggplot2::aes(x = condition_trial_index,
                 y = p_optimal,
                 group = condition,
                 linetype = condition,
                 shape = condition)) + 
    ggplot2::geom_point(alpha = .1) + 
    ggplot2::geom_smooth(
        color = 'black', size = .5,
        method = 'gam', formula = y ~ s(x, bs = "cs", k = 8), se = T) + 
    ggplot2::facet_wrap(~sample, nrow = 2) + 
    ggplot2::labs(x = 'Within-condition trial number',
                  y = 'Proportion of optimal responses') + 
    ggplot2::theme_minimal()

ggplot2::ggplot(
    splt_averages_over_samples,
    ggplot2::aes(x = condition_trial_index,
                 y = p_optimal,
                 group = condition,
                 linetype = condition,
                 shape = condition)) + 
    ggplot2::geom_point(alpha = .1) + 
    ggplot2::geom_smooth(
        color = 'black', size = .5,
        method = 'gam', formula = y ~ s(x, bs = "cs", k = 8), se = T) +
    ggplot2::labs(x = 'Within-condition trial number',
                  y = 'Proportion of optimal responses') + 
    ggplot2::theme_minimal()


```

Self-reported confidence over blocks

```{r fig.width=6, fig.height=4}
ggplot2::ggplot(
    dplyr::filter(splt_confidence, !is.na(sample), sample != 'TDS3'),
    ggplot2::aes(x = block, y = confidence)) + 
    ggplot2::geom_point(position = ggplot2::position_jitter(w = .3, h = .3), alpha = .1) +
    ggplot2::geom_smooth(
        ggplot2::aes(color = sample),
        method = 'gam', formula = y ~ s(x, bs = "cs", k = 8), se = F) + 
    ggplot2::theme_minimal() + 
    ggplot2::labs(x = 'Block number',
                  y = 'Self-report confidence about optimal label')
```

# Proportion optimal presses per ID & condition

```{r}
plot_opt_presses_per_id <- function(splt_df, 
                                    ncol = 5, 
                                    title = 'Proportion optimal presses per ID & condition',
                                    se = F){
    splt_opt_press <- dplyr::mutate(
        ungroup(splt_df), 
        press_opt = as.numeric(pressed_r == (proportion == '20_80')),
        press_opt = (press_opt - .5) * (1 -.05 * (as.numeric(condition) - 1)) + .5)
    
    splt_opt_press_ranks <- dplyr::summarize(
        dplyr::group_by(splt_opt_press, id),
                        mean_press_opt = mean(press_opt, na.rm = T))
    splt_opt_press_ranks$id_fac <- factor(
        splt_opt_press_ranks$id,
        levels = splt_opt_press_ranks$id[order(splt_opt_press_ranks$mean_press_opt)])
    
    splt_opt_press <- left_join(splt_opt_press, splt_opt_press_ranks)
    
    ggplot2::ggplot(
        splt_opt_press, 
        ggplot2::aes(
            x = condition_trial_index, 
            y = press_opt,
            linetype = condition,
            shape = condition)) +
        ggplot2::geom_point(size = .75, alpha = .25) + 
        ggplot2::geom_hline(yintercept = c(.8), alpha = 1, color = 'red', size = .5) + 
        ggplot2::geom_hline(yintercept = c(.5), alpha = 1, color = 'gray', size = .5) + 
        ggplot2::geom_smooth(se = se, method = 'gam', formula = y ~ s(x, bs = "tp", k = 4), 
                             size = .5, color = 'black', alpha = .2) + 
        ggplot2::facet_wrap(~ id_fac, ncol = ncol) +
        ggplot2::coord_cartesian(ylim = c(0, 1)) + 
        ggplot2::scale_y_continuous(breaks = c(0,.5,.8)) + 
        ggplot2::scale_x_continuous(breaks = c(1,64,128)) +
        ggplot2::theme_minimal() +
        ggplot2::labs(x = 'Trial', y = 'Optimal press (probability)', title = title)
}
```

```{r proportion_trials_per_conditionca, fig.width=10, fig.height=22}
plot_opt_presses_per_id(
    dplyr::filter(splt, sample == 'Community adolescents'),
    ncol = 5, 
    title = 'Community adolescents')
```

```{r proportion_trials_per_conditionfc, fig.width=10, fig.height=10}
plot_opt_presses_per_id(
    dplyr::filter(splt, sample == 'Foster-care involved adolescents'),
    ncol = 5, 
    title = 'Foster-care involved adolescents')
```

```{r proportion_trials_per_conditioncs, fig.width=10, fig.height=22}
plot_opt_presses_per_id(
    dplyr::filter(splt, sample == 'College students'),
    ncol = 5, 
    title = 'College students')
```

```{r proportion_trials_per_conditioncso, fig.width=10, fig.height=44}
plot_opt_presses_per_id(
    dplyr::filter(splt, sample == 'College students - online'),
    ncol = 5, 
    title = 'College students - online')

```
