---
title: "Fit model to participant data"
author: "John Flournoy"
date: "`r Sys.Date()`"
output: 
  bookdown::html_document2:
    base_format: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo=F,message=F,warning=F,error=F
)
```

# Method

Using the model presented in the section on [testing simulated data](test-simulated-data.html), I estimate the posterior distribution of the model parameters given the data provided by four groups of participants.
Quality of estimation can be supported by (A), (B), (C), (D).


```{r}
library(rstan)

stanfit <- readRDS('/data/jflournoy/split/probly/splt-tght-rl_2_level_no_b-1522879.RDS')
```

```{r diag}
munames <- grep('mu', names(stanfit), value = T)
betanames <- grep('beta', names(stanfit), value = T)
taunames <- grep('tau_\\w{2,3}\\[', names(stanfit), value = T)
lomeganames <- grep('L_Omega', names(stanfit), value = T)

rstan::stan_diag(stanfit, information = 'sample')
rstan::stan_diag(stanfit, information = 'stepsize')
rstan::stan_diag(stanfit, information = 'treedepth')
rstan::stan_diag(stanfit, information = 'divergence')

for(i in 1:length(munames)){
    rstan::stan_par(stanfit, par = munames[i])
}
rstan::stan_rhat(stanfit, pars = munames)
rstan::stan_ess(stanfit, pars = munames)
pairs(stanfit, pars = munames, condition = 'accept_stat__')

for(i in 1:(length(betanames)/313)){
    thesebetanames <- betanames[(313*(i-1) + 1):(313*i)]
    print(
        rstan::stan_rhat(
            stanfit, 
            pars = thesebetanames, binwidth = .005) + 
            geom_vline(xintercept = 1.1) + 
            labs(title = paste0('Rhat: ', thesebetanames[1])))
    print(
        rstan::stan_ess(
            stanfit, 
            pars = thesebetanames, binwidth = .01) + 
            geom_vline(xintercept = .001) + 
            labs(title = paste0('ESS: ', thesebetanames[1])))
}


```

```{r pairs, fig.width=15, fig.height=15}
pairs(stanfit, pars = munames)
pairs(stanfit, pars = taunames)
pairs(stanfit, pars = lomeganames, log = T)

ep_cor_cov_samps <- probly::extract_cor_cov_samps(stanfit, par_subscript = 'ep')

thing <- as.data.frame(t(apply(ep_cor_cov_samps$Sigma, 3, function(x) {
    d <- c(x[lower.tri(x)], diag(x))
    names(d) <- c('[2,1]', '[3,1]', '[3,2]', '[1,1]', '[2,2]', '[3,3]')
    d
})))

bayesplot::mcmc_pairs(thing)
```
