---
title: "Test Simulated Model Data"
author: "John Flournoy"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Generate data where there are 3 conditions, and individual variation in probability of choosing 'left' for each condition. Set the mean probability of left for each condition to values in `beta_mu` below.

```{r}
set.seed(150319/2018)
j <- 300 #number of subjects
t <- 100 #number of trials
g <- 4 #number of subsamples
c <- 3 #number of conditions
n <- t*c*j #number of observations
gg <- sample(1:g, size = j, replace = T) #group IDs

hyper_gamma_mu <- c(-1, 0, 1) #The mean population effect
hyper_gamma_sigma <- 1
gamma_mu <- matrix(rnorm(c*g, hyper_gamma_mu, hyper_gamma_sigma), nrow = g, byrow = T) #specific sample mean effects
gamma_sigma <- matrix(
    c(1, .2, .2,
      .2, 1, .2,
      .2, .2, 1),
    nrow = 3, byrow = T
) #correlation among random effects at between individuals in the same sample

beta_j <- t(apply(gamma_mu[gg,], 1, function(mu) {MASS::mvrnorm(1, mu, gamma_sigma)}))

beta_j_df <- as.data.frame(beta_j)
beta_j_df$b0 <- beta_j_df[,1]
beta_j_df$b1 <- beta_j_df[,2] - beta_j_df[,1]
beta_j_df$b2 <- beta_j_df[,3] - beta_j_df[,1]

summary(beta_j_df)
cor(beta_j_df[,1:3])
cor(beta_j_df[,4:6])

lapply(1:g, function(grp) cor(beta_j_df[gg == grp,1:3]))

dd <- data.frame(id = as.factor(1:j),
                 grp = as.factor(gg),
                 condition = as.factor(rep(rep(1:3, each = n/j/3), each = j)))

design <- model.matrix(~ 0 + id:condition, dd)

dd$theta <-  design %*% as.vector(beta_j)

dd$p <- arm::invlogit(dd$theta)
dd$y <- rbinom(dim(dd)[1], 1, dd$p)
```

```{r}
library(lme4)
library(brms)
library(rstan)
library(future)
plan('multiprocess')

glm_fit <- glm(y ~ 1 + condition, data = dd, family = 'binomial')

lme4_fit_fn <- '/data/jflournoy/split/probly/lme4_test_fit.RDS'
lme4_fit_future <- future::future(
    CachedFit(
        {
            lme4::glmer(y ~ 1 + condition + (1 + condition | grp/id), data = dd, family = 'binomial')
        },
        rds_filename = lme4_fit_fn))

brms_fit_fn <- '/data/jflournoy/split/probly/brms_test_fit.RDS'
brms_fit_future <- future::future(
    CachedFit(
        {
            brms::brm(y ~ 1 + condition + (1 + condition | grp/id), data = dd, family = 'bernoulli',
                      chains = 4, iter = 1000, cores = 4, 
                      save_model = '../exec/brms_test_model.stan')
        },
        rds_filename = brms_fit_fn))

summary(glm_fit)
dplyr::summarize(dplyr::group_by(dd, condition), mean = mean(y))
rbind(
    c(coef(glm_fit)[1], sum(coef(glm_fit)[1:2]), sum(coef(glm_fit)[c(1,3)])),
    arm::invlogit(c(coef(glm_fit)[1], sum(coef(glm_fit)[1:2]), sum(coef(glm_fit)[c(1,3)]))))

if(resolved(lme4_fit_future)){
    lme4_fit <- future::value(lme4_fit_future)
    print(summary(lme4_fit))
    rbind(
        c(fixef(lme4_fit)[1], sum(fixef(lme4_fit)[1:2]), sum(fixef(lme4_fit)[c(1,3)])),
        arm::invlogit(c(fixef(lme4_fit)[1], sum(fixef(lme4_fit)[1:2]), sum(fixef(lme4_fit)[c(1,3)]))))
}
if(resolved(brms_fit_future)){
    brms_fit <- future::value(brms_fit_future)
    summary(brms_fit)
}
```


```{r test-stan-mvnorm}
# data {
#   int<lower=1> N; //number of subjects
#   int<lower=1> T; //max number of trials
#   int<lower=2> K; //number of trial predictors (in this case, conditions)
#   int<lower=1> L; //number if subject-level predictors. 1 = intercept only
#   int<lower=1,upper=T> Tsubj[N]; //trials per subject
#   int<lower=-1,upper=1> press_right[N,T]; //choices "0" = left, "1" = right
#   int<lower=-1,upper=3> condition[N,T]; //1 = ctrl, 2 = mateseeking, 3 = status
#   matrix[N, L] u; //group predictors. u[,1] = 1 for intercept
# }
press_right_mat <- matrix(dd$y, nrow = j)
condition_mat <- matrix(as.numeric(dd$condition), nrow = j)
data_for_stan <- list(
    N = j,
    T = t*3,
    K = 3,
    L = 1,
    Tsubj = rep(t*3, j),
    press_right = press_right_mat,
    condition = condition_mat,
    u = matrix(rep(1, j*1, nrow = j))
)

stan_fit_fn <- '/data/jflournoy/split/probly/stan_test_fit.RDS'
if(!file.exists()){
    stan_fit <- rstan::stan(file = '../exec/splt_rl_mvnorm_test.stan',
                            data = data_for_stan, chains = 4, iter = 8000,
                            cores = 4)
    saveRDS(stan_fit, stan_fit_fn)
} else {
    stan_fit <- readRDS(stan_fit_fn)
}

stan_fit@model_pars
gamma_fit_summary <- summary(stan_fit, pars = c('gamma'))
gamma_fit_summary$summary
arm::invlogit(gamma_fit_summary$summary[, 'mean'])
mean(data_for_stan$press_right[data_for_stan$condition==1])
mean(data_for_stan$press_right[data_for_stan$condition==2])
mean(data_for_stan$press_right[data_for_stan$condition==3])
rstan::traceplot(stan_fit, pars = 'gamma')
beta_fit_summary <- summary(stan_fit, pars = c('beta'))
arm::invlogit(mean(beta_fit_summary$summary[grepl(',1\\]', rownames(beta_fit_summary$summary)), 'mean']))
```

