<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Fundamental Social Motives Confirmatory Factor Analysis • probly</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js" integrity="sha384-cV+rhyOuRHc9Ub/91rihWcGmMmCXDeksTtCihMupQHSsi8GIIRDG0ThDc3HGQFJ3" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../jquery.sticky-kit.min.js"></script><script src="../pkgdown.js"></script><meta property="og:title" content="Fundamental Social Motives Confirmatory Factor Analysis">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">probly</a>
        <span class="label label-default" data-toggle="tooltip" data-placement="bottom" title="Released package">0.1.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/age-and-puberty-data.html">Age, Puberty, and Informant Data</a>
    </li>
    <li>
      <a href="../articles/age-learning-association.html">Association of age with learning parameters</a>
    </li>
    <li>
      <a href="../articles/collect-data.html">Collect and Clean SPLT Data</a>
    </li>
    <li>
      <a href="../articles/descriptive-statistics.html">Descriptive Statistics for SPLT data</a>
    </li>
    <li>
      <a href="../articles/fit-model-to-participant-data.html">Fit model to participant data</a>
    </li>
    <li>
      <a href="../articles/fsmi-cfa.html">Fundamental Social Motives Confirmatory Factor Analysis</a>
    </li>
    <li>
      <a href="../articles/fsmi-data.html">Retrieve Fundamental Social Motives Data</a>
    </li>
    <li>
      <a href="../articles/test-simple-3l-mv-model.html">Test Simple 3-level Multivariate Normal Model</a>
    </li>
    <li>
      <a href="../articles/test-simulated-data.html">Test Simulated Data</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Fundamental Social Motives Confirmatory Factor Analysis</h1>
                        <h4 class="author">John Flournoy</h4>
            
            <h4 class="date">2018-05-08</h4>
      
      
      <div class="hidden name"><code>fsmi-cfa.Rmd</code></div>

    </div>

    
    
<p>Below, I begin to examine the fit of scales measuring behaviors, beliefs, attitudes, and strategies relevant to mate-seeking and status motives. After examining the item distributions to see if there are any very problematic subsets, I fit a confirmatory factor analysis to remaining scales. I also confirm that an exploratory factor analysis shows expected factor structure.</p>
<div id="checking-items" class="section level1">
<h1 class="hasAnchor">
<a href="#checking-items" class="anchor"></a>Checking Items</h1>
<div id="fsmi" class="section level2">
<h2 class="hasAnchor">
<a href="#fsmi" class="anchor"></a>FSMI</h2>
<p><img src="fsmi-cfa_files/figure-html/unnamed-chunk-1-1.png" width="768"></p>
<p>The CFA will not include kin care (missing data), family care (highly skewed), and mate retention general (highly skewed).</p>
</div>
<div id="dominance-and-prestige" class="section level2">
<h2 class="hasAnchor">
<a href="#dominance-and-prestige" class="anchor"></a>Dominance and Prestige</h2>
<p><img src="fsmi-cfa_files/figure-html/unnamed-chunk-2-1.png" width="576"></p>
</div>
<div id="kids-social-reward-questionnaire" class="section level2">
<h2 class="hasAnchor">
<a href="#kids-social-reward-questionnaire" class="anchor"></a>Kids social reward questionnaire</h2>
<p><img src="fsmi-cfa_files/figure-html/unnamed-chunk-3-1.png" width="960"></p>
<p>The CFA will not include negative social potency (highly skewed), or prosocial iteractions (highly skewed). Target scales to use for status and mate seeking motives are the admiration scale, passivity scale, sexual relationshups scale, and sociability scale.</p>
</div>
<div id="social-achievement-goals" class="section level2">
<h2 class="hasAnchor">
<a href="#social-achievement-goals" class="anchor"></a>Social achievement goals</h2>
<p><img src="fsmi-cfa_files/figure-html/unnamed-chunk-4-1.png" width="672"></p>
</div>
<div id="urgency-premeditation-perseverance-and-sensation-seeking" class="section level2">
<h2 class="hasAnchor">
<a href="#urgency-premeditation-perseverance-and-sensation-seeking" class="anchor"></a>Urgency, Premeditation, Perseverance, and Sensation Seeking</h2>
<p><img src="fsmi-cfa_files/figure-html/unnamed-chunk-5-1.png" width="768"></p>
</div>
</div>
<div id="confirmatory-factor-analyses-and-exploration" class="section level1">
<h1 class="hasAnchor">
<a href="#confirmatory-factor-analyses-and-exploration" class="anchor"></a>Confirmatory factor analyses and exploration</h1>
<div id="fsmi-1" class="section level2">
<h2 class="hasAnchor">
<a href="#fsmi-1" class="anchor"></a>FSMI</h2>
<table class="table">
<thead><tr class="header">
<th></th>
<th align="right">Df</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">Chisq</th>
<th align="right">Chisq diff</th>
<th align="right">Df diff</th>
<th align="right">Pr(&gt;Chisq)</th>
<th align="right">cfi</th>
<th align="right">rmsea</th>
<th align="right">mfi</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>fsmi_cfa_method</td>
<td align="right">1004</td>
<td align="right">35415.74</td>
<td align="right">36167.29</td>
<td align="right">1685.742</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">NA</td>
<td align="right">0.864</td>
<td align="right">0.055</td>
<td align="right">0.220</td>
</tr>
<tr class="even">
<td>fsmi_cfa</td>
<td align="right">1052</td>
<td align="right">35670.44</td>
<td align="right">36258.01</td>
<td align="right">2036.439</td>
<td align="right">2408.134</td>
<td align="right">48</td>
<td align="right">0</td>
<td align="right">0.804</td>
<td align="right">0.064</td>
<td align="right">0.112</td>
</tr>
</tbody>
</table>
<pre><code>#&gt; lavaan (0.6-1.1193) converged normally after  97 iterations
#&gt; 
#&gt;                                                   Used       Total
#&gt;   Number of observations                           225         335
#&gt;   Number of missing patterns                        22
#&gt; 
#&gt;   Estimator                                         ML      Robust
#&gt;   Model Fit Test Statistic                    2036.439    3150.679
#&gt;   Degrees of freedom                              1052        1052
#&gt;   P-value (Chi-square)                           0.000       0.000
#&gt;   Scaling correction factor                                  0.646
#&gt;     for the Yuan-Bentler correction
#&gt; 
#&gt; Parameter Estimates:
#&gt; 
#&gt;   Information                                 Observed
#&gt;   Observed information based on                Hessian
#&gt;   Standard Errors                   Robust.huber.white
#&gt; 
#&gt; Latent Variables:
#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
#&gt;   fsmi_affgrp =~                                                        
#&gt;     fsmi_qs_31        0.916    0.096    9.519    0.000    0.916    0.685
#&gt;     fsmi_qs_32        1.098    0.087   12.587    0.000    1.098    0.768
#&gt;     fsmi_qs_33        1.052    0.090   11.745    0.000    1.052    0.832
#&gt;     fsmi_qs_34       -0.706    0.132   -5.347    0.000   -0.706   -0.466
#&gt;     fsmi_qs_35        0.502    0.092    5.431    0.000    0.502    0.472
#&gt;     fsmi_qs_36        0.600    0.115    5.193    0.000    0.600    0.483
#&gt;   fsmi_affexc =~                                                        
#&gt;     fsmi_qs_37        1.141    0.102   11.190    0.000    1.141    0.779
#&gt;     fsmi_qs_38        1.214    0.095   12.764    0.000    1.214    0.801
#&gt;     fsmi_qs_39        1.015    0.101   10.033    0.000    1.015    0.766
#&gt;     fsmi_qs_40        1.044    0.134    7.795    0.000    1.044    0.650
#&gt;     fsmi_qs_41        1.017    0.128    7.919    0.000    1.017    0.600
#&gt;     fsmi_qs_42        0.981    0.153    6.402    0.000    0.981    0.624
#&gt;   fsmi_affind =~                                                        
#&gt;     fsmi_qs_43        1.191    0.117   10.197    0.000    1.191    0.753
#&gt;     fsmi_qs_44        0.973    0.118    8.278    0.000    0.973    0.647
#&gt;     fsmi_qs_45        0.908    0.121    7.507    0.000    0.908    0.559
#&gt;     fsmi_qs_46        1.177    0.117   10.060    0.000    1.177    0.707
#&gt;     fsmi_qs_47        0.875    0.127    6.917    0.000    0.875    0.634
#&gt;     fsmi_qs_48        1.105    0.116    9.564    0.000    1.105    0.756
#&gt;   fsmi_dis =~                                                           
#&gt;     fsmi_qs_25       -0.893    0.126   -7.065    0.000   -0.893   -0.562
#&gt;     fsmi_qs_26       -0.943    0.117   -8.052    0.000   -0.943   -0.615
#&gt;     fsmi_qs_27       -0.979    0.135   -7.235    0.000   -0.979   -0.602
#&gt;     fsmi_qs_28        1.219    0.093   13.126    0.000    1.219    0.764
#&gt;     fsmi_qs_29        1.030    0.105    9.841    0.000    1.030    0.683
#&gt;     fsmi_qs_30        1.222    0.096   12.770    0.000    1.222    0.785
#&gt;   fsmi_retbrk =~                                                        
#&gt;     fsmi_qs_7         1.457    0.072   20.280    0.000    1.457    0.842
#&gt;     fsmi_qs_8         1.145    0.109   10.524    0.000    1.145    0.689
#&gt;     fsmi_qs_9         1.397    0.084   16.588    0.000    1.397    0.855
#&gt;     fsmi_qs_10        1.466    0.084   17.505    0.000    1.466    0.856
#&gt;     fsmi_qs_11        0.905    0.108    8.421    0.000    0.905    0.582
#&gt;     fsmi_qs_12        1.134    0.098   11.575    0.000    1.134    0.733
#&gt;   fsmi_prot =~                                                          
#&gt;     fsmi_qs_19        1.273    0.085   14.902    0.000    1.273    0.805
#&gt;     fsmi_qs_20        0.942    0.086   10.901    0.000    0.942    0.710
#&gt;     fsmi_qs_21       -0.672    0.105   -6.427    0.000   -0.672   -0.502
#&gt;     fsmi_qs_22        1.122    0.089   12.652    0.000    1.122    0.736
#&gt;     fsmi_qs_23        1.203    0.091   13.199    0.000    1.203    0.795
#&gt;     fsmi_qs_24        0.976    0.086   11.364    0.000    0.976    0.735
#&gt;   fsmi_stat =~                                                          
#&gt;     fsmi_qs_49        0.838    0.127    6.603    0.000    0.838    0.575
#&gt;     fsmi_qs_50        0.729    0.114    6.384    0.000    0.729    0.531
#&gt;     fsmi_qs_51        0.796    0.102    7.787    0.000    0.796    0.624
#&gt;     fsmi_qs_52        0.827    0.117    7.056    0.000    0.827    0.584
#&gt;     fsmi_qs_53        0.837    0.111    7.525    0.000    0.837    0.610
#&gt;     fsmi_qs_54       -0.433    0.151   -2.875    0.004   -0.433   -0.314
#&gt;   fsmi_mate =~                                                          
#&gt;     fsmi_qs_55        1.411    0.091   15.438    0.000    1.411    0.764
#&gt;     fsmi_qs_56        1.891    0.075   25.122    0.000    1.891    0.913
#&gt;     fsmi_qs_57       -1.439    0.112  -12.903    0.000   -1.439   -0.723
#&gt;     fsmi_qs_58       -1.022    0.120   -8.495    0.000   -1.022   -0.576
#&gt;     fsmi_qs_59       -0.931    0.133   -6.995    0.000   -0.931   -0.507
#&gt;     fsmi_qs_60        1.905    0.068   28.195    0.000    1.905    0.917
#&gt; 
#&gt; Covariances:
#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
#&gt;   fsmi_affgrp ~~                                                        
#&gt;     fsmi_affexc       0.418    0.093    4.494    0.000    0.418    0.418
#&gt;     fsmi_affind      -0.404    0.096   -4.208    0.000   -0.404   -0.404
#&gt;     fsmi_dis          0.130    0.073    1.787    0.074    0.130    0.130
#&gt;     fsmi_retbrk       0.140    0.081    1.729    0.084    0.140    0.140
#&gt;     fsmi_prot         0.190    0.086    2.218    0.027    0.190    0.190
#&gt;     fsmi_stat         0.385    0.103    3.722    0.000    0.385    0.385
#&gt;     fsmi_mate         0.191    0.071    2.671    0.008    0.191    0.191
#&gt;   fsmi_affexc ~~                                                        
#&gt;     fsmi_affind      -0.158    0.093   -1.706    0.088   -0.158   -0.158
#&gt;     fsmi_dis         -0.061    0.086   -0.709    0.478   -0.061   -0.061
#&gt;     fsmi_retbrk       0.293    0.095    3.088    0.002    0.293    0.293
#&gt;     fsmi_prot         0.151    0.087    1.743    0.081    0.151    0.151
#&gt;     fsmi_stat         0.349    0.110    3.170    0.002    0.349    0.349
#&gt;     fsmi_mate         0.211    0.077    2.740    0.006    0.211    0.211
#&gt;   fsmi_affind ~~                                                        
#&gt;     fsmi_dis         -0.089    0.088   -1.015    0.310   -0.089   -0.089
#&gt;     fsmi_retbrk       0.107    0.083    1.282    0.200    0.107    0.107
#&gt;     fsmi_prot         0.140    0.094    1.488    0.137    0.140    0.140
#&gt;     fsmi_stat        -0.003    0.103   -0.029    0.977   -0.003   -0.003
#&gt;     fsmi_mate        -0.087    0.074   -1.181    0.238   -0.087   -0.087
#&gt;   fsmi_dis ~~                                                           
#&gt;     fsmi_retbrk       0.055    0.094    0.585    0.559    0.055    0.055
#&gt;     fsmi_prot        -0.220    0.097   -2.276    0.023   -0.220   -0.220
#&gt;     fsmi_stat         0.029    0.094    0.310    0.757    0.029    0.029
#&gt;     fsmi_mate         0.092    0.080    1.151    0.250    0.092    0.092
#&gt;   fsmi_retbrk ~~                                                        
#&gt;     fsmi_prot         0.097    0.086    1.128    0.260    0.097    0.097
#&gt;     fsmi_stat         0.114    0.092    1.235    0.217    0.114    0.114
#&gt;     fsmi_mate         0.386    0.071    5.392    0.000    0.386    0.386
#&gt;   fsmi_prot ~~                                                          
#&gt;     fsmi_stat         0.322    0.083    3.879    0.000    0.322    0.322
#&gt;     fsmi_mate        -0.117    0.079   -1.487    0.137   -0.117   -0.117
#&gt;   fsmi_stat ~~                                                          
#&gt;     fsmi_mate         0.114    0.086    1.316    0.188    0.114    0.114
#&gt; 
#&gt; Intercepts:
#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
#&gt;    .fsmi_qs_31        5.030    0.089   56.282    0.000    5.030    3.760
#&gt;    .fsmi_qs_32        5.009    0.095   52.548    0.000    5.009    3.503
#&gt;    .fsmi_qs_33        5.440    0.084   64.561    0.000    5.440    4.304
#&gt;    .fsmi_qs_34        3.733    0.101   36.979    0.000    3.733    2.465
#&gt;    .fsmi_qs_35        5.480    0.071   77.341    0.000    5.480    5.156
#&gt;    .fsmi_qs_36        5.600    0.083   67.738    0.000    5.600    4.516
#&gt;    .fsmi_qs_37        4.904    0.098   49.898    0.000    4.904    3.350
#&gt;    .fsmi_qs_38        4.710    0.102   46.238    0.000    4.710    3.107
#&gt;    .fsmi_qs_39        4.932    0.089   55.435    0.000    4.932    3.720
#&gt;    .fsmi_qs_40        4.793    0.108   44.368    0.000    4.793    2.982
#&gt;    .fsmi_qs_41        4.324    0.114   37.852    0.000    4.324    2.549
#&gt;    .fsmi_qs_42        4.819    0.106   45.619    0.000    4.819    3.064
#&gt;    .fsmi_qs_43        3.714    0.106   35.164    0.000    3.714    2.349
#&gt;    .fsmi_qs_44        3.107    0.101   30.856    0.000    3.107    2.065
#&gt;    .fsmi_qs_45        3.313    0.109   30.526    0.000    3.313    2.039
#&gt;    .fsmi_qs_46        4.737    0.111   42.608    0.000    4.737    2.847
#&gt;    .fsmi_qs_47        5.331    0.092   57.844    0.000    5.331    3.861
#&gt;    .fsmi_qs_48        4.796    0.097   49.219    0.000    4.796    3.281
#&gt;    .fsmi_qs_25        4.044    0.106   38.198    0.000    4.044    2.547
#&gt;    .fsmi_qs_26        4.605    0.103   44.885    0.000    4.605    3.003
#&gt;    .fsmi_qs_27        3.564    0.109   32.813    0.000    3.564    2.191
#&gt;    .fsmi_qs_28        3.884    0.107   36.366    0.000    3.884    2.435
#&gt;    .fsmi_qs_29        3.784    0.101   37.572    0.000    3.784    2.509
#&gt;    .fsmi_qs_30        3.888    0.104   37.347    0.000    3.888    2.499
#&gt;    .fsmi_qs_7         3.564    0.117   30.567    0.000    3.564    2.059
#&gt;    .fsmi_qs_8         3.594    0.112   32.058    0.000    3.594    2.163
#&gt;    .fsmi_qs_9         3.509    0.110   31.830    0.000    3.509    2.147
#&gt;    .fsmi_qs_10        3.651    0.116   31.597    0.000    3.651    2.131
#&gt;    .fsmi_qs_11        3.787    0.105   36.109    0.000    3.787    2.437
#&gt;    .fsmi_qs_12        3.458    0.104   33.194    0.000    3.458    2.236
#&gt;    .fsmi_qs_19        4.627    0.106   43.783    0.000    4.627    2.924
#&gt;    .fsmi_qs_20        4.945    0.088   55.885    0.000    4.945    3.729
#&gt;    .fsmi_qs_21        3.040    0.089   34.088    0.000    3.040    2.273
#&gt;    .fsmi_qs_22        4.633    0.102   45.503    0.000    4.633    3.040
#&gt;    .fsmi_qs_23        4.956    0.101   49.106    0.000    4.956    3.274
#&gt;    .fsmi_qs_24        5.258    0.089   59.282    0.000    5.258    3.959
#&gt;    .fsmi_qs_49        4.638    0.097   47.690    0.000    4.638    3.184
#&gt;    .fsmi_qs_50        5.021    0.092   54.459    0.000    5.021    3.655
#&gt;    .fsmi_qs_51        4.707    0.085   55.255    0.000    4.707    3.691
#&gt;    .fsmi_qs_52        4.242    0.095   44.889    0.000    4.242    2.998
#&gt;    .fsmi_qs_53        5.044    0.091   55.149    0.000    5.044    3.677
#&gt;    .fsmi_qs_54        4.183    0.092   45.326    0.000    4.183    3.028
#&gt;    .fsmi_qs_55        3.545    0.123   28.756    0.000    3.545    1.919
#&gt;    .fsmi_qs_56        3.820    0.138   27.604    0.000    3.820    1.844
#&gt;    .fsmi_qs_57        3.667    0.133   27.623    0.000    3.667    1.842
#&gt;    .fsmi_qs_58        4.649    0.119   39.143    0.000    4.649    2.622
#&gt;    .fsmi_qs_59        3.402    0.122   27.820    0.000    3.402    1.854
#&gt;    .fsmi_qs_60        3.622    0.138   26.156    0.000    3.622    1.744
#&gt;     fsmi_affgrp       0.000                               0.000    0.000
#&gt;     fsmi_affexc       0.000                               0.000    0.000
#&gt;     fsmi_affind       0.000                               0.000    0.000
#&gt;     fsmi_dis          0.000                               0.000    0.000
#&gt;     fsmi_retbrk       0.000                               0.000    0.000
#&gt;     fsmi_prot         0.000                               0.000    0.000
#&gt;     fsmi_stat         0.000                               0.000    0.000
#&gt;     fsmi_mate         0.000                               0.000    0.000
#&gt; 
#&gt; Variances:
#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
#&gt;    .fsmi_qs_31        0.951    0.140    6.797    0.000    0.951    0.531
#&gt;    .fsmi_qs_32        0.839    0.142    5.921    0.000    0.839    0.410
#&gt;    .fsmi_qs_33        0.492    0.092    5.371    0.000    0.492    0.308
#&gt;    .fsmi_qs_34        1.794    0.216    8.305    0.000    1.794    0.782
#&gt;    .fsmi_qs_35        0.878    0.106    8.251    0.000    0.878    0.777
#&gt;    .fsmi_qs_36        1.178    0.191    6.158    0.000    1.178    0.766
#&gt;    .fsmi_qs_37        0.842    0.164    5.134    0.000    0.842    0.393
#&gt;    .fsmi_qs_38        0.825    0.173    4.768    0.000    0.825    0.359
#&gt;    .fsmi_qs_39        0.727    0.108    6.734    0.000    0.727    0.414
#&gt;    .fsmi_qs_40        1.493    0.233    6.396    0.000    1.493    0.578
#&gt;    .fsmi_qs_41        1.843    0.249    7.387    0.000    1.843    0.640
#&gt;    .fsmi_qs_42        1.511    0.282    5.362    0.000    1.511    0.611
#&gt;    .fsmi_qs_43        1.082    0.231    4.674    0.000    1.082    0.433
#&gt;    .fsmi_qs_44        1.317    0.195    6.742    0.000    1.317    0.582
#&gt;    .fsmi_qs_45        1.816    0.204    8.918    0.000    1.816    0.688
#&gt;    .fsmi_qs_46        1.384    0.225    6.151    0.000    1.384    0.500
#&gt;    .fsmi_qs_47        1.141    0.216    5.291    0.000    1.141    0.598
#&gt;    .fsmi_qs_48        0.915    0.217    4.213    0.000    0.915    0.428
#&gt;    .fsmi_qs_25        1.725    0.211    8.160    0.000    1.725    0.684
#&gt;    .fsmi_qs_26        1.462    0.226    6.458    0.000    1.462    0.622
#&gt;    .fsmi_qs_27        1.688    0.240    7.037    0.000    1.688    0.638
#&gt;    .fsmi_qs_28        1.059    0.188    5.641    0.000    1.059    0.416
#&gt;    .fsmi_qs_29        1.214    0.197    6.173    0.000    1.214    0.534
#&gt;    .fsmi_qs_30        0.929    0.176    5.269    0.000    0.929    0.384
#&gt;    .fsmi_qs_7         0.874    0.113    7.712    0.000    0.874    0.291
#&gt;    .fsmi_qs_8         1.451    0.213    6.812    0.000    1.451    0.525
#&gt;    .fsmi_qs_9         0.720    0.136    5.289    0.000    0.720    0.269
#&gt;    .fsmi_qs_10        0.785    0.159    4.932    0.000    0.785    0.267
#&gt;    .fsmi_qs_11        1.596    0.175    9.101    0.000    1.596    0.661
#&gt;    .fsmi_qs_12        1.107    0.186    5.938    0.000    1.107    0.463
#&gt;    .fsmi_qs_19        0.884    0.175    5.041    0.000    0.884    0.353
#&gt;    .fsmi_qs_20        0.872    0.116    7.524    0.000    0.872    0.496
#&gt;    .fsmi_qs_21        1.338    0.157    8.501    0.000    1.338    0.748
#&gt;    .fsmi_qs_22        1.063    0.157    6.783    0.000    1.063    0.458
#&gt;    .fsmi_qs_23        0.843    0.135    6.243    0.000    0.843    0.368
#&gt;    .fsmi_qs_24        0.812    0.137    5.938    0.000    0.812    0.460
#&gt;    .fsmi_qs_49        1.419    0.220    6.463    0.000    1.419    0.669
#&gt;    .fsmi_qs_50        1.355    0.169    8.008    0.000    1.355    0.718
#&gt;    .fsmi_qs_51        0.993    0.154    6.432    0.000    0.993    0.611
#&gt;    .fsmi_qs_52        1.319    0.182    7.240    0.000    1.319    0.659
#&gt;    .fsmi_qs_53        1.183    0.161    7.335    0.000    1.183    0.628
#&gt;    .fsmi_qs_54        1.720    0.192    8.940    0.000    1.720    0.902
#&gt;    .fsmi_qs_55        1.420    0.178    7.989    0.000    1.420    0.416
#&gt;    .fsmi_qs_56        0.717    0.175    4.088    0.000    0.717    0.167
#&gt;    .fsmi_qs_57        1.893    0.271    6.982    0.000    1.893    0.477
#&gt;    .fsmi_qs_58        2.099    0.294    7.132    0.000    2.099    0.668
#&gt;    .fsmi_qs_59        2.501    0.260    9.635    0.000    2.501    0.743
#&gt;    .fsmi_qs_60        0.687    0.152    4.503    0.000    0.687    0.159
#&gt;     fsmi_affgrp       1.000                               1.000    1.000
#&gt;     fsmi_affexc       1.000                               1.000    1.000
#&gt;     fsmi_affind       1.000                               1.000    1.000
#&gt;     fsmi_dis          1.000                               1.000    1.000
#&gt;     fsmi_retbrk       1.000                               1.000    1.000
#&gt;     fsmi_prot         1.000                               1.000    1.000
#&gt;     fsmi_stat         1.000                               1.000    1.000
#&gt;     fsmi_mate         1.000                               1.000    1.000
#&gt; lavaan (0.6-1.1193) converged normally after 121 iterations
#&gt; 
#&gt;                                                   Used       Total
#&gt;   Number of observations                           225         335
#&gt;   Number of missing patterns                        22
#&gt; 
#&gt;   Estimator                                         ML      Robust
#&gt;   Model Fit Test Statistic                    1685.742    2514.951
#&gt;   Degrees of freedom                              1004        1004
#&gt;   P-value (Chi-square)                           0.000       0.000
#&gt;   Scaling correction factor                                  0.670
#&gt;     for the Yuan-Bentler correction
#&gt; 
#&gt; Parameter Estimates:
#&gt; 
#&gt;   Information                                 Observed
#&gt;   Observed information based on                Hessian
#&gt;   Standard Errors                   Robust.huber.white
#&gt; 
#&gt; Latent Variables:
#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
#&gt;   fsmi_affgrp =~                                                        
#&gt;     fsmi_qs_31        0.729    0.091    7.973    0.000    0.729    0.545
#&gt;     fsmi_qs_32        1.075    0.084   12.803    0.000    1.075    0.752
#&gt;     fsmi_qs_33        1.030    0.076   13.483    0.000    1.030    0.815
#&gt;     fsmi_qs_34       -0.856    0.115   -7.419    0.000   -0.856   -0.565
#&gt;     fsmi_qs_35        0.445    0.080    5.532    0.000    0.445    0.419
#&gt;     fsmi_qs_36        0.432    0.103    4.184    0.000    0.432    0.348
#&gt;   fsmi_affexc =~                                                        
#&gt;     fsmi_qs_37        0.603    0.181    3.338    0.001    0.603    0.412
#&gt;     fsmi_qs_38        0.627    0.186    3.379    0.001    0.627    0.414
#&gt;     fsmi_qs_39        0.480    0.155    3.099    0.002    0.480    0.362
#&gt;     fsmi_qs_40       -0.372    0.181   -2.061    0.039   -0.372   -0.231
#&gt;     fsmi_qs_41       -0.324    0.217   -1.491    0.136   -0.324   -0.191
#&gt;     fsmi_qs_42       -0.559    0.201   -2.789    0.005   -0.559   -0.355
#&gt;   fsmi_affind =~                                                        
#&gt;     fsmi_qs_43        1.172    0.124    9.433    0.000    1.172    0.741
#&gt;     fsmi_qs_44        0.954    0.120    7.942    0.000    0.954    0.634
#&gt;     fsmi_qs_45        0.873    0.126    6.948    0.000    0.873    0.537
#&gt;     fsmi_qs_46        1.180    0.111   10.598    0.000    1.180    0.709
#&gt;     fsmi_qs_47        0.916    0.125    7.323    0.000    0.916    0.664
#&gt;     fsmi_qs_48        1.119    0.114    9.844    0.000    1.119    0.766
#&gt;   fsmi_dis =~                                                           
#&gt;     fsmi_qs_25       -0.871    0.122   -7.170    0.000   -0.871   -0.549
#&gt;     fsmi_qs_26       -0.926    0.111   -8.310    0.000   -0.926   -0.604
#&gt;     fsmi_qs_27       -0.959    0.130   -7.369    0.000   -0.959   -0.589
#&gt;     fsmi_qs_28        1.218    0.094   12.954    0.000    1.218    0.763
#&gt;     fsmi_qs_29        1.048    0.102   10.256    0.000    1.048    0.695
#&gt;     fsmi_qs_30        1.234    0.095   12.954    0.000    1.234    0.793
#&gt;   fsmi_retbrk =~                                                        
#&gt;     fsmi_qs_7         1.330    0.086   15.450    0.000    1.330    0.769
#&gt;     fsmi_qs_8         0.970    0.124    7.837    0.000    0.970    0.584
#&gt;     fsmi_qs_9         1.362    0.084   16.228    0.000    1.362    0.834
#&gt;     fsmi_qs_10        1.349    0.094   14.309    0.000    1.349    0.788
#&gt;     fsmi_qs_11        0.787    0.115    6.863    0.000    0.787    0.506
#&gt;     fsmi_qs_12        1.108    0.096   11.516    0.000    1.108    0.717
#&gt;   fsmi_prot =~                                                          
#&gt;     fsmi_qs_19        1.245    0.090   13.766    0.000    1.245    0.787
#&gt;     fsmi_qs_20        0.928    0.088   10.489    0.000    0.928    0.700
#&gt;     fsmi_qs_21       -0.676    0.109   -6.229    0.000   -0.676   -0.505
#&gt;     fsmi_qs_22        1.060    0.097   10.914    0.000    1.060    0.696
#&gt;     fsmi_qs_23        1.184    0.095   12.462    0.000    1.184    0.782
#&gt;     fsmi_qs_24        0.984    0.088   11.231    0.000    0.984    0.740
#&gt;   fsmi_stat =~                                                          
#&gt;     fsmi_qs_49        0.794    0.126    6.320    0.000    0.794    0.545
#&gt;     fsmi_qs_50        0.897    0.113    7.910    0.000    0.897    0.651
#&gt;     fsmi_qs_51        0.794    0.105    7.566    0.000    0.794    0.623
#&gt;     fsmi_qs_52        0.631    0.118    5.351    0.000    0.631    0.446
#&gt;     fsmi_qs_53        0.749    0.111    6.731    0.000    0.749    0.546
#&gt;     fsmi_qs_54       -0.289    0.145   -1.994    0.046   -0.289   -0.209
#&gt;   fsmi_mate =~                                                          
#&gt;     fsmi_qs_55        1.350    0.097   13.948    0.000    1.350    0.731
#&gt;     fsmi_qs_56        1.841    0.081   22.791    0.000    1.841    0.888
#&gt;     fsmi_qs_57       -1.418    0.114  -12.469    0.000   -1.418   -0.712
#&gt;     fsmi_qs_58       -1.040    0.114   -9.140    0.000   -1.040   -0.587
#&gt;     fsmi_qs_59       -0.906    0.135   -6.725    0.000   -0.906   -0.494
#&gt;     fsmi_qs_60        1.874    0.070   26.628    0.000    1.874    0.902
#&gt;   fsmi_bifac =~                                                         
#&gt;     fsmi_qs_31        0.620    0.114    5.446    0.000    0.620    0.464
#&gt;     fsmi_qs_32        0.315    0.138    2.287    0.022    0.315    0.221
#&gt;     fsmi_qs_33        0.277    0.142    1.954    0.051    0.277    0.219
#&gt;     fsmi_qs_34        0.142    0.126    1.128    0.259    0.142    0.094
#&gt;     fsmi_qs_35        0.213    0.104    2.054    0.040    0.213    0.200
#&gt;     fsmi_qs_36        0.505    0.121    4.191    0.000    0.505    0.407
#&gt;     fsmi_qs_37        1.030    0.129    8.009    0.000    1.030    0.704
#&gt;     fsmi_qs_38        1.114    0.120    9.245    0.000    1.114    0.735
#&gt;     fsmi_qs_39        0.927    0.121    7.656    0.000    0.927    0.700
#&gt;     fsmi_qs_40        1.222    0.109   11.181    0.000    1.222    0.760
#&gt;     fsmi_qs_41        1.118    0.107   10.435    0.000    1.118    0.659
#&gt;     fsmi_qs_42        1.205    0.113   10.707    0.000    1.205    0.765
#&gt;     fsmi_qs_43       -0.043    0.159   -0.270    0.787   -0.043   -0.027
#&gt;     fsmi_qs_44       -0.097    0.142   -0.682    0.496   -0.097   -0.065
#&gt;     fsmi_qs_45       -0.499    0.148   -3.382    0.001   -0.499   -0.307
#&gt;     fsmi_qs_46       -0.214    0.135   -1.590    0.112   -0.214   -0.129
#&gt;     fsmi_qs_47        0.201    0.138    1.460    0.144    0.201    0.146
#&gt;     fsmi_qs_48       -0.012    0.141   -0.087    0.931   -0.012   -0.008
#&gt;     fsmi_qs_25        0.272    0.119    2.281    0.023    0.272    0.171
#&gt;     fsmi_qs_26        0.258    0.131    1.963    0.050    0.258    0.168
#&gt;     fsmi_qs_27        0.247    0.132    1.863    0.063    0.247    0.152
#&gt;     fsmi_qs_28       -0.058    0.129   -0.446    0.656   -0.058   -0.036
#&gt;     fsmi_qs_29        0.086    0.123    0.704    0.482    0.086    0.057
#&gt;     fsmi_qs_30        0.017    0.137    0.127    0.899    0.017    0.011
#&gt;     fsmi_qs_7         0.584    0.142    4.109    0.000    0.584    0.338
#&gt;     fsmi_qs_8         0.637    0.132    4.826    0.000    0.637    0.384
#&gt;     fsmi_qs_9         0.384    0.138    2.780    0.005    0.384    0.235
#&gt;     fsmi_qs_10        0.571    0.142    4.028    0.000    0.571    0.333
#&gt;     fsmi_qs_11        0.446    0.133    3.344    0.001    0.446    0.287
#&gt;     fsmi_qs_12        0.284    0.135    2.109    0.035    0.284    0.184
#&gt;     fsmi_qs_19        0.259    0.129    2.009    0.045    0.259    0.163
#&gt;     fsmi_qs_20        0.167    0.105    1.582    0.114    0.167    0.126
#&gt;     fsmi_qs_21       -0.049    0.108   -0.456    0.648   -0.049   -0.037
#&gt;     fsmi_qs_22        0.428    0.129    3.327    0.001    0.428    0.281
#&gt;     fsmi_qs_23        0.215    0.130    1.653    0.098    0.215    0.142
#&gt;     fsmi_qs_24        0.086    0.102    0.848    0.396    0.086    0.065
#&gt;     fsmi_qs_49        0.318    0.137    2.321    0.020    0.318    0.218
#&gt;     fsmi_qs_50       -0.066    0.131   -0.501    0.616   -0.066   -0.048
#&gt;     fsmi_qs_51        0.176    0.112    1.570    0.116    0.176    0.138
#&gt;     fsmi_qs_52        0.530    0.107    4.970    0.000    0.530    0.375
#&gt;     fsmi_qs_53        0.333    0.122    2.735    0.006    0.333    0.243
#&gt;     fsmi_qs_54       -0.360    0.121   -2.971    0.003   -0.360   -0.261
#&gt;     fsmi_qs_55        0.432    0.138    3.129    0.002    0.432    0.234
#&gt;     fsmi_qs_56        0.433    0.158    2.748    0.006    0.433    0.209
#&gt;     fsmi_qs_57       -0.252    0.154   -1.639    0.101   -0.252   -0.127
#&gt;     fsmi_qs_58       -0.039    0.154   -0.252    0.801   -0.039   -0.022
#&gt;     fsmi_qs_59       -0.217    0.162   -1.333    0.182   -0.217   -0.118
#&gt;     fsmi_qs_60        0.351    0.144    2.441    0.015    0.351    0.169
#&gt; 
#&gt; Covariances:
#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
#&gt;   fsmi_affgrp ~~                                                        
#&gt;     fsmi_bifac        0.000                               0.000    0.000
#&gt;   fsmi_affexc ~~                                                        
#&gt;     fsmi_bifac        0.000                               0.000    0.000
#&gt;   fsmi_affind ~~                                                        
#&gt;     fsmi_bifac        0.000                               0.000    0.000
#&gt;   fsmi_dis ~~                                                           
#&gt;     fsmi_bifac        0.000                               0.000    0.000
#&gt;   fsmi_retbrk ~~                                                        
#&gt;     fsmi_bifac        0.000                               0.000    0.000
#&gt;   fsmi_prot ~~                                                          
#&gt;     fsmi_bifac        0.000                               0.000    0.000
#&gt;   fsmi_stat ~~                                                          
#&gt;     fsmi_bifac        0.000                               0.000    0.000
#&gt;   fsmi_mate ~~                                                          
#&gt;     fsmi_bifac        0.000                               0.000    0.000
#&gt;   fsmi_affgrp ~~                                                        
#&gt;     fsmi_affexc       0.276    0.110    2.522    0.012    0.276    0.276
#&gt;     fsmi_affind      -0.388    0.102   -3.803    0.000   -0.388   -0.388
#&gt;     fsmi_dis          0.168    0.075    2.238    0.025    0.168    0.168
#&gt;     fsmi_retbrk       0.015    0.080    0.190    0.849    0.015    0.015
#&gt;     fsmi_prot         0.125    0.087    1.442    0.149    0.125    0.125
#&gt;     fsmi_stat         0.296    0.105    2.811    0.005    0.296    0.296
#&gt;     fsmi_mate         0.126    0.075    1.671    0.095    0.126    0.126
#&gt;   fsmi_affexc ~~                                                        
#&gt;     fsmi_affind      -0.375    0.088   -4.261    0.000   -0.375   -0.375
#&gt;     fsmi_dis          0.042    0.097    0.431    0.666    0.042    0.042
#&gt;     fsmi_retbrk      -0.310    0.090   -3.445    0.001   -0.310   -0.310
#&gt;     fsmi_prot        -0.107    0.099   -1.079    0.281   -0.107   -0.107
#&gt;     fsmi_stat         0.136    0.106    1.279    0.201    0.136    0.136
#&gt;     fsmi_mate        -0.031    0.100   -0.307    0.759   -0.031   -0.031
#&gt;   fsmi_affind ~~                                                        
#&gt;     fsmi_dis         -0.090    0.088   -1.020    0.308   -0.090   -0.090
#&gt;     fsmi_retbrk       0.140    0.089    1.575    0.115    0.140    0.140
#&gt;     fsmi_prot         0.158    0.091    1.750    0.080    0.158    0.158
#&gt;     fsmi_stat         0.046    0.106    0.435    0.663    0.046    0.046
#&gt;     fsmi_mate        -0.072    0.076   -0.950    0.342   -0.072   -0.072
#&gt;   fsmi_dis ~~                                                           
#&gt;     fsmi_retbrk       0.092    0.093    0.998    0.318    0.092    0.092
#&gt;     fsmi_prot        -0.206    0.100   -2.070    0.038   -0.206   -0.206
#&gt;     fsmi_stat         0.050    0.098    0.514    0.607    0.050    0.050
#&gt;     fsmi_mate         0.111    0.079    1.401    0.161    0.111    0.111
#&gt;   fsmi_retbrk ~~                                                        
#&gt;     fsmi_prot         0.021    0.089    0.241    0.810    0.021    0.021
#&gt;     fsmi_stat        -0.011    0.100   -0.114    0.909   -0.011   -0.011
#&gt;     fsmi_mate         0.339    0.078    4.341    0.000    0.339    0.339
#&gt;   fsmi_prot ~~                                                          
#&gt;     fsmi_stat         0.280    0.089    3.141    0.002    0.280    0.280
#&gt;     fsmi_mate        -0.165    0.076   -2.164    0.030   -0.165   -0.165
#&gt;   fsmi_stat ~~                                                          
#&gt;     fsmi_mate         0.047    0.094    0.498    0.619    0.047    0.047
#&gt; 
#&gt; Intercepts:
#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
#&gt;    .fsmi_qs_31        5.028    0.089   56.246    0.000    5.028    3.763
#&gt;    .fsmi_qs_32        5.009    0.095   52.548    0.000    5.009    3.503
#&gt;    .fsmi_qs_33        5.440    0.084   64.561    0.000    5.440    4.304
#&gt;    .fsmi_qs_34        3.733    0.101   36.979    0.000    3.733    2.465
#&gt;    .fsmi_qs_35        5.480    0.071   77.341    0.000    5.480    5.156
#&gt;    .fsmi_qs_36        5.600    0.083   67.738    0.000    5.600    4.516
#&gt;    .fsmi_qs_37        4.900    0.098   49.773    0.000    4.900    3.347
#&gt;    .fsmi_qs_38        4.705    0.102   46.159    0.000    4.705    3.105
#&gt;    .fsmi_qs_39        4.927    0.089   55.300    0.000    4.927    3.720
#&gt;    .fsmi_qs_40        4.796    0.108   44.236    0.000    4.796    2.982
#&gt;    .fsmi_qs_41        4.321    0.114   37.786    0.000    4.321    2.547
#&gt;    .fsmi_qs_42        4.821    0.106   45.463    0.000    4.821    3.062
#&gt;    .fsmi_qs_43        3.714    0.106   35.177    0.000    3.714    2.349
#&gt;    .fsmi_qs_44        3.107    0.101   30.861    0.000    3.107    2.066
#&gt;    .fsmi_qs_45        3.314    0.109   30.524    0.000    3.314    2.039
#&gt;    .fsmi_qs_46        4.738    0.111   42.632    0.000    4.738    2.847
#&gt;    .fsmi_qs_47        5.330    0.092   57.792    0.000    5.330    3.861
#&gt;    .fsmi_qs_48        4.796    0.097   49.219    0.000    4.796    3.281
#&gt;    .fsmi_qs_25        4.044    0.106   38.198    0.000    4.044    2.547
#&gt;    .fsmi_qs_26        4.604    0.103   44.831    0.000    4.604    3.002
#&gt;    .fsmi_qs_27        3.563    0.109   32.808    0.000    3.563    2.190
#&gt;    .fsmi_qs_28        3.884    0.107   36.365    0.000    3.884    2.434
#&gt;    .fsmi_qs_29        3.784    0.101   37.550    0.000    3.784    2.509
#&gt;    .fsmi_qs_30        3.889    0.104   37.336    0.000    3.889    2.499
#&gt;    .fsmi_qs_7         3.562    0.116   30.586    0.000    3.562    2.059
#&gt;    .fsmi_qs_8         3.592    0.112   32.079    0.000    3.592    2.163
#&gt;    .fsmi_qs_9         3.507    0.110   31.862    0.000    3.507    2.147
#&gt;    .fsmi_qs_10        3.648    0.115   31.630    0.000    3.648    2.131
#&gt;    .fsmi_qs_11        3.784    0.105   36.073    0.000    3.784    2.434
#&gt;    .fsmi_qs_12        3.458    0.104   33.258    0.000    3.458    2.240
#&gt;    .fsmi_qs_19        4.627    0.106   43.746    0.000    4.627    2.923
#&gt;    .fsmi_qs_20        4.945    0.088   55.891    0.000    4.945    3.728
#&gt;    .fsmi_qs_21        3.040    0.089   34.088    0.000    3.040    2.273
#&gt;    .fsmi_qs_22        4.632    0.102   45.468    0.000    4.632    3.038
#&gt;    .fsmi_qs_23        4.956    0.101   49.106    0.000    4.956    3.274
#&gt;    .fsmi_qs_24        5.259    0.089   59.296    0.000    5.259    3.959
#&gt;    .fsmi_qs_49        4.637    0.097   47.688    0.000    4.637    3.184
#&gt;    .fsmi_qs_50        5.029    0.092   54.623    0.000    5.029    3.650
#&gt;    .fsmi_qs_51        4.707    0.085   55.299    0.000    4.707    3.693
#&gt;    .fsmi_qs_52        4.243    0.095   44.898    0.000    4.243    2.998
#&gt;    .fsmi_qs_53        5.044    0.091   55.149    0.000    5.044    3.677
#&gt;    .fsmi_qs_54        4.184    0.092   45.325    0.000    4.184    3.029
#&gt;    .fsmi_qs_55        3.545    0.123   28.751    0.000    3.545    1.919
#&gt;    .fsmi_qs_56        3.820    0.138   27.599    0.000    3.820    1.843
#&gt;    .fsmi_qs_57        3.667    0.133   27.623    0.000    3.667    1.842
#&gt;    .fsmi_qs_58        4.649    0.119   39.140    0.000    4.649    2.622
#&gt;    .fsmi_qs_59        3.402    0.122   27.820    0.000    3.402    1.854
#&gt;    .fsmi_qs_60        3.622    0.138   26.156    0.000    3.622    1.744
#&gt;     fsmi_affgrp       0.000                               0.000    0.000
#&gt;     fsmi_affexc       0.000                               0.000    0.000
#&gt;     fsmi_affind       0.000                               0.000    0.000
#&gt;     fsmi_dis          0.000                               0.000    0.000
#&gt;     fsmi_retbrk       0.000                               0.000    0.000
#&gt;     fsmi_prot         0.000                               0.000    0.000
#&gt;     fsmi_stat         0.000                               0.000    0.000
#&gt;     fsmi_mate         0.000                               0.000    0.000
#&gt;     fsmi_bifac        0.000                               0.000    0.000
#&gt; 
#&gt; Variances:
#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
#&gt;    .fsmi_qs_31        0.870    0.120    7.230    0.000    0.870    0.487
#&gt;    .fsmi_qs_32        0.789    0.137    5.756    0.000    0.789    0.386
#&gt;    .fsmi_qs_33        0.460    0.085    5.437    0.000    0.460    0.288
#&gt;    .fsmi_qs_34        1.541    0.202    7.633    0.000    1.541    0.672
#&gt;    .fsmi_qs_35        0.886    0.106    8.329    0.000    0.886    0.785
#&gt;    .fsmi_qs_36        1.096    0.165    6.635    0.000    1.096    0.713
#&gt;    .fsmi_qs_37        0.718    0.148    4.841    0.000    0.718    0.335
#&gt;    .fsmi_qs_38        0.663    0.135    4.926    0.000    0.663    0.289
#&gt;    .fsmi_qs_39        0.665    0.124    5.381    0.000    0.665    0.379
#&gt;    .fsmi_qs_40        0.954    0.162    5.905    0.000    0.954    0.369
#&gt;    .fsmi_qs_41        1.522    0.214    7.117    0.000    1.522    0.529
#&gt;    .fsmi_qs_42        0.714    0.168    4.242    0.000    0.714    0.288
#&gt;    .fsmi_qs_43        1.125    0.248    4.543    0.000    1.125    0.450
#&gt;    .fsmi_qs_44        1.343    0.197    6.830    0.000    1.343    0.594
#&gt;    .fsmi_qs_45        1.629    0.196    8.325    0.000    1.629    0.617
#&gt;    .fsmi_qs_46        1.330    0.215    6.183    0.000    1.330    0.480
#&gt;    .fsmi_qs_47        1.026    0.174    5.908    0.000    1.026    0.538
#&gt;    .fsmi_qs_48        0.884    0.209    4.233    0.000    0.884    0.414
#&gt;    .fsmi_qs_25        1.689    0.193    8.763    0.000    1.689    0.670
#&gt;    .fsmi_qs_26        1.429    0.202    7.088    0.000    1.429    0.608
#&gt;    .fsmi_qs_27        1.667    0.224    7.430    0.000    1.667    0.630
#&gt;    .fsmi_qs_28        1.060    0.187    5.680    0.000    1.060    0.416
#&gt;    .fsmi_qs_29        1.168    0.193    6.062    0.000    1.168    0.514
#&gt;    .fsmi_qs_30        0.900    0.174    5.182    0.000    0.900    0.372
#&gt;    .fsmi_qs_7         0.880    0.113    7.769    0.000    0.880    0.294
#&gt;    .fsmi_qs_8         1.410    0.203    6.949    0.000    1.410    0.511
#&gt;    .fsmi_qs_9         0.665    0.131    5.075    0.000    0.665    0.249
#&gt;    .fsmi_qs_10        0.784    0.156    5.021    0.000    0.784    0.268
#&gt;    .fsmi_qs_11        1.600    0.173    9.247    0.000    1.600    0.662
#&gt;    .fsmi_qs_12        1.076    0.173    6.203    0.000    1.076    0.451
#&gt;    .fsmi_qs_19        0.888    0.178    4.990    0.000    0.888    0.354
#&gt;    .fsmi_qs_20        0.870    0.118    7.384    0.000    0.870    0.494
#&gt;    .fsmi_qs_21        1.330    0.158    8.393    0.000    1.330    0.743
#&gt;    .fsmi_qs_22        1.017    0.144    7.069    0.000    1.017    0.437
#&gt;    .fsmi_qs_23        0.843    0.139    6.047    0.000    0.843    0.368
#&gt;    .fsmi_qs_24        0.790    0.135    5.832    0.000    0.790    0.448
#&gt;    .fsmi_qs_49        1.391    0.218    6.387    0.000    1.391    0.656
#&gt;    .fsmi_qs_50        1.090    0.170    6.427    0.000    1.090    0.574
#&gt;    .fsmi_qs_51        0.963    0.155    6.200    0.000    0.963    0.593
#&gt;    .fsmi_qs_52        1.324    0.153    8.652    0.000    1.324    0.661
#&gt;    .fsmi_qs_53        1.211    0.160    7.563    0.000    1.211    0.643
#&gt;    .fsmi_qs_54        1.694    0.186    9.094    0.000    1.694    0.888
#&gt;    .fsmi_qs_55        1.403    0.177    7.923    0.000    1.403    0.411
#&gt;    .fsmi_qs_56        0.719    0.174    4.123    0.000    0.719    0.167
#&gt;    .fsmi_qs_57        1.891    0.269    7.023    0.000    1.891    0.477
#&gt;    .fsmi_qs_58        2.060    0.280    7.356    0.000    2.060    0.655
#&gt;    .fsmi_qs_59        2.500    0.259    9.652    0.000    2.500    0.742
#&gt;    .fsmi_qs_60        0.679    0.154    4.410    0.000    0.679    0.157
#&gt;     fsmi_affgrp       1.000                               1.000    1.000
#&gt;     fsmi_affexc       1.000                               1.000    1.000
#&gt;     fsmi_affind       1.000                               1.000    1.000
#&gt;     fsmi_dis          1.000                               1.000    1.000
#&gt;     fsmi_retbrk       1.000                               1.000    1.000
#&gt;     fsmi_prot         1.000                               1.000    1.000
#&gt;     fsmi_stat         1.000                               1.000    1.000
#&gt;     fsmi_mate         1.000                               1.000    1.000
#&gt;     fsmi_bifac        1.000                               1.000    1.000</code></pre>
<p>A model for the FSMI scale without a method bifactor fits substantially worse than that with the method factor.</p>
<table class="table">
<thead><tr class="header">
<th></th>
<th align="right">Df</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">Chisq</th>
<th align="right">Chisq diff</th>
<th align="right">Df diff</th>
<th align="right">Pr(&gt;Chisq)</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>fsmi_cfa_method</td>
<td align="right">1004</td>
<td align="right">35415.74</td>
<td align="right">36167.29</td>
<td align="right">1685.742</td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
</tr>
<tr class="even">
<td>fsmi_cfa</td>
<td align="right">1052</td>
<td align="right">35670.44</td>
<td align="right">36258.01</td>
<td align="right">2036.439</td>
<td align="right">2408.134</td>
<td align="right">48</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<table class="table">
<thead><tr class="header">
<th></th>
<th align="right">rmsea</th>
<th align="right">mfi</th>
<th align="right">gammaHat</th>
<th align="right">adjGammaHat</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>baseline</td>
<td align="right">0.0644904</td>
<td align="right">0.1121809</td>
<td align="right">0.8452247</td>
<td align="right">0.8269812</td>
</tr>
<tr class="even">
<td>bifac</td>
<td align="right">0.0549353</td>
<td align="right">0.2198122</td>
<td align="right">0.8874594</td>
<td align="right">0.8681796</td>
</tr>
</tbody>
</table>
<p>Exploratory factor analysis (not shown, but code for which is above) results in 8 factors, with high loadings grouped as expected and minimal cross loadings &gt; .25. The bifactor rotation (with 9 factors) also shows this pattern.</p>

<div class="figure">
<span id="fig:fsmicfaplot1"></span>
<img src="fsmi-cfa_files/figure-html/fsmicfaplot1-1.png" alt="FSMI CFA with method bifactor. Path weight reflects standardized loading strength, with minimum cuttoff for showing path set at .20, and maximum weight at .90 (apparent for several mate-seeking items). Residual and means not shown." width="768"><p class="caption">
Figure 1: FSMI CFA with method bifactor. Path weight reflects standardized loading strength, with minimum cuttoff for showing path set at .20, and maximum weight at .90 (apparent for several mate-seeking items). Residual and means not shown.
</p>
</div>

<div class="figure">
<span id="fig:fsmicfaplot2"></span>
<img src="fsmi-cfa_files/figure-html/fsmicfaplot2-1.png" alt="FSMI CFA. Path weight reflects standardized loading strength, with minimum cuttoff for showing path set at .20, and maximum weight at .90 (apparent for several mate-seeking items). Residual and means not shown." width="768"><p class="caption">
Figure 2: FSMI CFA. Path weight reflects standardized loading strength, with minimum cuttoff for showing path set at .20, and maximum weight at .90 (apparent for several mate-seeking items). Residual and means not shown.
</p>
</div>
<p>The two factor structures are shown above.</p>
<div id="fsmi-discussion" class="section level3">
<h3 class="hasAnchor">
<a href="#fsmi-discussion" class="anchor"></a>FSMI Discussion</h3>
<p>The factor model, fit to all but three of the original scale’s factors (child-care, care for family, general mate retention; N = 225) shows somewhat reasonable, but not great, fit (RMSEA = 0.064, <span class="math inline">\(\hat\gamma\)</span> = 0.845).
This deviates from the results reported by Neel and colleagues <span class="citation">(2015)</span>, where each factor, or set of related factors, was tested independently.
A parallel scree plot analysis (psych package version 1.7.8) suggested 8 factors, with all item loadings dominant on expected factors.
There is some evidence that including a factor that accounts for an overall method factor improve model fit.
Adding such a method bifactor improved the fit somewhat (RMSEA = 0.055, <span class="math inline">\(\hat\gamma\)</span> = 0.887).
Model comparison substantially favors the less parsimonious model that includes the method bifactor (<span class="math inline">\(\Delta\)</span>AIC = 255, <span class="math inline">\(\Delta\)</span>BIC = 91, <span class="math inline">\(\Delta\)</span>Df = 48).
Although this bifactor does improve fit across all factors, it does not load strongly on either status or mate-seeking, so I do not account for in in analyses below.</p>

<div class="figure">
<span id="fig:fsmicfamatestatplot"></span>
<img src="fsmi-cfa_files/figure-html/fsmicfamatestatplot-1.png" alt="FSMI mate-seeking &amp; status CFA. Path weights and labels reflect standardized loading strength. Residuals, exogenous variances, and means not shown." width="768"><p class="caption">
Figure 3: FSMI mate-seeking &amp; status CFA. Path weights and labels reflect standardized loading strength. Residuals, exogenous variances, and means not shown.
</p>
</div>
<p>A CFA for mate-seeking and status factors fit well (RMSEA = 0.051, <span class="math inline">\(\hat\gamma\)</span> = 0.977), with the two factors showing a small, positive, non-significant correlation (<span class="math inline">\(r = 0.11, Z = 1.27\)</span>).</p>
<p>Note that item 54, “I do not worry very much about losing status” has a particularly low loading on the status factor.</p>
</div>
</div>
<div id="k-srq" class="section level2">
<h2 class="hasAnchor">
<a href="#k-srq" class="anchor"></a>K-SRQ</h2>
<pre><code>#&gt; lavaan (0.6-1.1193) converged normally after  58 iterations
#&gt; 
#&gt;                                                   Used       Total
#&gt;   Number of observations                           320         335
#&gt;   Number of missing patterns                         9
#&gt; 
#&gt;   Estimator                                         ML      Robust
#&gt;   Model Fit Test Statistic                     135.714      99.834
#&gt;   Degrees of freedom                                59          59
#&gt;   P-value (Chi-square)                           0.000       0.001
#&gt;   Scaling correction factor                                  1.359
#&gt;     for the Yuan-Bentler correction
#&gt; 
#&gt; Parameter Estimates:
#&gt; 
#&gt;   Information                                 Observed
#&gt;   Observed information based on                Hessian
#&gt;   Standard Errors                   Robust.huber.white
#&gt; 
#&gt; Latent Variables:
#&gt;                                 Estimate  Std.Err  z-value  P(&gt;|z|)
#&gt;   k_srq_admiration =~                                              
#&gt;     K_SRQ_1                        0.934    0.081   11.518    0.000
#&gt;     K_SRQ_7                        0.940    0.071   13.219    0.000
#&gt;     K_SRQ_11                       1.067    0.069   15.516    0.000
#&gt;     K_SRQ_18                       0.983    0.071   13.833    0.000
#&gt;   k_srq_passivity =~                                               
#&gt;     K_SRQ_12                       1.182    0.090   13.202    0.000
#&gt;     K_SRQ_21                       1.274    0.098   13.029    0.000
#&gt;     K_SRQ_23                       0.947    0.082   11.597    0.000
#&gt;   k_srq_sexual_relationships =~                                    
#&gt;     K_SRQ_9                        1.000    0.095   10.549    0.000
#&gt;     K_SRQ_13                       0.921    0.093    9.860    0.000
#&gt;     K_SRQ_20                       1.210    0.086   14.074    0.000
#&gt;   k_srq_sociability =~                                             
#&gt;     K_SRQ_4                        0.939    0.123    7.651    0.000
#&gt;     K_SRQ_10                       0.753    0.099    7.581    0.000
#&gt;     K_SRQ_15                       0.998    0.084   11.882    0.000
#&gt;    Std.lv  Std.all
#&gt;                   
#&gt;     0.934    0.764
#&gt;     0.940    0.755
#&gt;     1.067    0.826
#&gt;     0.983    0.745
#&gt;                   
#&gt;     1.182    0.763
#&gt;     1.274    0.784
#&gt;     0.947    0.648
#&gt;                   
#&gt;     1.000    0.651
#&gt;     0.921    0.715
#&gt;     1.210    0.788
#&gt;                   
#&gt;     0.939    0.535
#&gt;     0.753    0.548
#&gt;     0.998    0.685
#&gt; 
#&gt; Covariances:
#&gt;                                 Estimate  Std.Err  z-value  P(&gt;|z|)
#&gt;   k_srq_admiration ~~                                              
#&gt;     k_srq_passivty                 0.030    0.078    0.381    0.703
#&gt;     k_srq_sxl_rltn                 0.639    0.063   10.187    0.000
#&gt;     k_srq_sociblty                 0.691    0.084    8.190    0.000
#&gt;   k_srq_passivity ~~                                               
#&gt;     k_srq_sxl_rltn                 0.146    0.075    1.964    0.050
#&gt;     k_srq_sociblty                 0.201    0.080    2.507    0.012
#&gt;   k_srq_sexual_relationships ~~                                    
#&gt;     k_srq_sociblty                 0.841    0.060   14.033    0.000
#&gt;    Std.lv  Std.all
#&gt;                   
#&gt;     0.030    0.030
#&gt;     0.639    0.639
#&gt;     0.691    0.691
#&gt;                   
#&gt;     0.146    0.146
#&gt;     0.201    0.201
#&gt;                   
#&gt;     0.841    0.841
#&gt; 
#&gt; Intercepts:
#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
#&gt;    .K_SRQ_1           5.728    0.068   83.897    0.000    5.728    4.690
#&gt;    .K_SRQ_7           5.459    0.070   78.282    0.000    5.459    4.383
#&gt;    .K_SRQ_11          5.491    0.072   76.035    0.000    5.491    4.250
#&gt;    .K_SRQ_18          5.424    0.074   73.287    0.000    5.424    4.111
#&gt;    .K_SRQ_12          3.019    0.087   34.860    0.000    3.019    1.949
#&gt;    .K_SRQ_21          3.095    0.091   34.060    0.000    3.095    1.905
#&gt;    .K_SRQ_23          3.359    0.082   40.853    0.000    3.359    2.298
#&gt;    .K_SRQ_9           5.145    0.088   58.200    0.000    5.145    3.348
#&gt;    .K_SRQ_13          5.863    0.072   81.250    0.000    5.863    4.553
#&gt;    .K_SRQ_20          5.317    0.086   61.867    0.000    5.317    3.465
#&gt;    .K_SRQ_4           4.706    0.098   47.812    0.000    4.706    2.680
#&gt;    .K_SRQ_10          5.482    0.077   71.273    0.000    5.482    3.985
#&gt;    .K_SRQ_15          5.542    0.082   67.910    0.000    5.542    3.803
#&gt;     k_srq_admiratn    0.000                               0.000    0.000
#&gt;     k_srq_passivty    0.000                               0.000    0.000
#&gt;     k_srq_sxl_rltn    0.000                               0.000    0.000
#&gt;     k_srq_sociblty    0.000                               0.000    0.000
#&gt; 
#&gt; Variances:
#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
#&gt;    .K_SRQ_1           0.620    0.107    5.780    0.000    0.620    0.416
#&gt;    .K_SRQ_7           0.667    0.110    6.090    0.000    0.667    0.430
#&gt;    .K_SRQ_11          0.530    0.087    6.087    0.000    0.530    0.318
#&gt;    .K_SRQ_18          0.774    0.118    6.553    0.000    0.774    0.445
#&gt;    .K_SRQ_12          1.002    0.188    5.341    0.000    1.002    0.418
#&gt;    .K_SRQ_21          1.016    0.213    4.768    0.000    1.016    0.385
#&gt;    .K_SRQ_23          1.240    0.130    9.530    0.000    1.240    0.580
#&gt;    .K_SRQ_9           1.361    0.191    7.119    0.000    1.361    0.577
#&gt;    .K_SRQ_13          0.811    0.098    8.296    0.000    0.811    0.489
#&gt;    .K_SRQ_20          0.891    0.150    5.941    0.000    0.891    0.378
#&gt;    .K_SRQ_4           2.202    0.236    9.345    0.000    2.202    0.714
#&gt;    .K_SRQ_10          1.325    0.154    8.616    0.000    1.325    0.700
#&gt;    .K_SRQ_15          1.127    0.174    6.481    0.000    1.127    0.531
#&gt;     k_srq_admiratn    1.000                               1.000    1.000
#&gt;     k_srq_passivty    1.000                               1.000    1.000
#&gt;     k_srq_sxl_rltn    1.000                               1.000    1.000
#&gt;     k_srq_sociblty    1.000                               1.000    1.000
#&gt; lavaan (0.6-1.1193) converged normally after  48 iterations
#&gt; 
#&gt;                                                   Used       Total
#&gt;   Number of observations                           320         335
#&gt;   Number of missing patterns                         9
#&gt; 
#&gt;   Estimator                                         ML      Robust
#&gt;   Model Fit Test Statistic                     148.324     112.093
#&gt;   Degrees of freedom                                62          62
#&gt;   P-value (Chi-square)                           0.000       0.000
#&gt;   Scaling correction factor                                  1.323
#&gt;     for the Yuan-Bentler correction
#&gt; 
#&gt; Parameter Estimates:
#&gt; 
#&gt;   Information                                 Observed
#&gt;   Observed information based on                Hessian
#&gt;   Standard Errors                   Robust.huber.white
#&gt; 
#&gt; Latent Variables:
#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
#&gt;   ML1 =~                                                                
#&gt;     K_SRQ_11          1.061    0.070   15.195    0.000    1.061    0.822
#&gt;     K_SRQ_18          0.967    0.073   13.267    0.000    0.967    0.733
#&gt;     K_SRQ_1           0.929    0.082   11.268    0.000    0.929    0.761
#&gt;     K_SRQ_7           0.954    0.070   13.697    0.000    0.954    0.766
#&gt;     K_SRQ_10          0.678    0.106    6.416    0.000    0.678    0.493
#&gt;   ML2 =~                                                                
#&gt;     K_SRQ_4           0.930    0.101    9.225    0.000    0.930    0.530
#&gt;     K_SRQ_20          1.200    0.086   13.972    0.000    1.200    0.782
#&gt;     K_SRQ_13          0.901    0.093    9.654    0.000    0.901    0.700
#&gt;     K_SRQ_9           0.995    0.093   10.681    0.000    0.995    0.647
#&gt;     K_SRQ_15          0.883    0.092    9.578    0.000    0.883    0.606
#&gt;   ML3 =~                                                                
#&gt;     K_SRQ_12          1.195    0.087   13.739    0.000    1.195    0.771
#&gt;     K_SRQ_21          1.261    0.095   13.317    0.000    1.261    0.777
#&gt;     K_SRQ_23          0.946    0.081   11.641    0.000    0.946    0.647
#&gt; 
#&gt; Covariances:
#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
#&gt;   ML1 ~~                                                                
#&gt;     ML2               0.665    0.059   11.294    0.000    0.665    0.665
#&gt;     ML3               0.037    0.077    0.484    0.629    0.037    0.037
#&gt;   ML2 ~~                                                                
#&gt;     ML3               0.170    0.070    2.418    0.016    0.170    0.170
#&gt; 
#&gt; Intercepts:
#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
#&gt;    .K_SRQ_11          5.491    0.072   76.035    0.000    5.491    4.250
#&gt;    .K_SRQ_18          5.424    0.074   73.270    0.000    5.424    4.110
#&gt;    .K_SRQ_1           5.728    0.068   83.897    0.000    5.728    4.690
#&gt;    .K_SRQ_7           5.459    0.070   78.286    0.000    5.459    4.383
#&gt;    .K_SRQ_10          5.479    0.077   71.173    0.000    5.479    3.984
#&gt;    .K_SRQ_4           4.706    0.098   47.852    0.000    4.706    2.681
#&gt;    .K_SRQ_20          5.317    0.086   61.862    0.000    5.317    3.465
#&gt;    .K_SRQ_13          5.863    0.072   81.227    0.000    5.863    4.552
#&gt;    .K_SRQ_9           5.142    0.088   58.111    0.000    5.142    3.344
#&gt;    .K_SRQ_15          5.543    0.082   67.942    0.000    5.543    3.805
#&gt;    .K_SRQ_12          3.019    0.087   34.860    0.000    3.019    1.949
#&gt;    .K_SRQ_21          3.095    0.091   34.061    0.000    3.095    1.906
#&gt;    .K_SRQ_23          3.359    0.082   40.857    0.000    3.359    2.298
#&gt;     ML1               0.000                               0.000    0.000
#&gt;     ML2               0.000                               0.000    0.000
#&gt;     ML3               0.000                               0.000    0.000
#&gt; 
#&gt; Variances:
#&gt;                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
#&gt;    .K_SRQ_11          0.542    0.085    6.366    0.000    0.542    0.325
#&gt;    .K_SRQ_18          0.806    0.121    6.665    0.000    0.806    0.463
#&gt;    .K_SRQ_1           0.628    0.110    5.731    0.000    0.628    0.421
#&gt;    .K_SRQ_7           0.640    0.102    6.275    0.000    0.640    0.413
#&gt;    .K_SRQ_10          1.431    0.158    9.063    0.000    1.431    0.757
#&gt;    .K_SRQ_4           2.216    0.197   11.275    0.000    2.216    0.719
#&gt;    .K_SRQ_20          0.914    0.142    6.419    0.000    0.914    0.388
#&gt;    .K_SRQ_13          0.846    0.095    8.925    0.000    0.846    0.510
#&gt;    .K_SRQ_9           1.375    0.185    7.417    0.000    1.375    0.581
#&gt;    .K_SRQ_15          1.343    0.167    8.052    0.000    1.343    0.633
#&gt;    .K_SRQ_12          0.971    0.183    5.315    0.000    0.971    0.405
#&gt;    .K_SRQ_21          1.047    0.204    5.133    0.000    1.047    0.397
#&gt;    .K_SRQ_23          1.241    0.129    9.633    0.000    1.241    0.581
#&gt;     ML1               1.000                               1.000    1.000
#&gt;     ML2               1.000                               1.000    1.000
#&gt;     ML3               1.000                               1.000    1.000</code></pre>

<div class="figure">
<span id="fig:ksrqcfaplot"></span>
<img src="fsmi-cfa_files/figure-html/ksrqcfaplot-1.png" alt="K-SRQ CFA. Path weights and labels reflect standardized loading strength. Residuals, exogenous variances, and means not shown." width="768"><p class="caption">
Figure 4: K-SRQ CFA. Path weights and labels reflect standardized loading strength. Residuals, exogenous variances, and means not shown.
</p>
</div>

<div class="figure">
<span id="fig:ksrq3faccfaplot"></span>
<img src="fsmi-cfa_files/figure-html/ksrq3faccfaplot-1.png" alt="K-SRQ CFA. Path weights and labels reflect standardized loading strength. Residuals, exogenous variances, and means not shown." width="768"><p class="caption">
Figure 5: K-SRQ CFA. Path weights and labels reflect standardized loading strength. Residuals, exogenous variances, and means not shown.
</p>
</div>

<table class="table">
<caption>
<span id="tab:unnamed-chunk-10">Table 1: </span>Correlations between FSMI and K-SRQ scales of interest.</caption>
<thead><tr class="header">
<th align="left">lhs</th>
<th align="left">op</th>
<th align="left">rhs</th>
<th align="left">est_rep_1</th>
<th align="left">est_rep_2</th>
<th align="right">std.all_1</th>
<th align="right">std.all_2</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">fsmi_mate</td>
<td align="left">~~</td>
<td align="left">fsmi_stat</td>
<td align="left">0.26 [ 0.03, 0.48]</td>
<td align="left">-0.06 [-0.31, 0.18]</td>
<td align="right">0.25</td>
<td align="right">-0.09</td>
</tr>
<tr class="even">
<td align="left">fsmi_mate</td>
<td align="left">~~</td>
<td align="left">k_srq_admiration</td>
<td align="left">0.39 [ 0.18, 0.59]</td>
<td align="left">-0.20 [-0.54, 0.14]</td>
<td align="right">0.35</td>
<td align="right">-0.27</td>
</tr>
<tr class="odd">
<td align="left">fsmi_mate</td>
<td align="left">~~</td>
<td align="left">k_srq_passivity</td>
<td align="left">0.46 [ 0.16, 0.76]</td>
<td align="left">0.06 [-0.24, 0.36]</td>
<td align="right">0.33</td>
<td align="right">0.07</td>
</tr>
<tr class="even">
<td align="left">fsmi_mate</td>
<td align="left">~~</td>
<td align="left">k_srq_sexual_relationships</td>
<td align="left">0.44 [ 0.16, 0.73]</td>
<td align="left">-0.19 [-0.54, 0.15]</td>
<td align="right">0.40</td>
<td align="right">-0.38</td>
</tr>
<tr class="odd">
<td align="left">fsmi_mate</td>
<td align="left">~~</td>
<td align="left">k_srq_sociability</td>
<td align="left">0.30 [ 0.09, 0.51]</td>
<td align="left">-0.18 [-0.52, 0.15]</td>
<td align="right">0.31</td>
<td align="right">-0.31</td>
</tr>
<tr class="even">
<td align="left">fsmi_stat</td>
<td align="left">~~</td>
<td align="left">k_srq_admiration</td>
<td align="left">0.57 [ 0.28, 0.86]</td>
<td align="left">0.68 [ 0.24, 1.13]</td>
<td align="right">0.68</td>
<td align="right">0.59</td>
</tr>
<tr class="odd">
<td align="left">fsmi_stat</td>
<td align="left">~~</td>
<td align="left">k_srq_passivity</td>
<td align="left">-0.06 [-0.30, 0.17]</td>
<td align="left">-0.35 [-0.90, 0.20]</td>
<td align="right">-0.06</td>
<td align="right">-0.28</td>
</tr>
<tr class="even">
<td align="left">fsmi_stat</td>
<td align="left">~~</td>
<td align="left">k_srq_sexual_relationships</td>
<td align="left">0.39 [ 0.12, 0.66]</td>
<td align="left">0.16 [-0.14, 0.47]</td>
<td align="right">0.47</td>
<td align="right">0.21</td>
</tr>
<tr class="odd">
<td align="left">fsmi_stat</td>
<td align="left">~~</td>
<td align="left">k_srq_sociability</td>
<td align="left">0.40 [ 0.15, 0.65]</td>
<td align="left">0.42 [ 0.09, 0.76]</td>
<td align="right">0.56</td>
<td align="right">0.47</td>
</tr>
<tr class="even">
<td align="left">k_srq_admiration</td>
<td align="left">~~</td>
<td align="left">k_srq_passivity</td>
<td align="left">0.24 [ 0.03, 0.45]</td>
<td align="left">-0.06 [-0.50, 0.39]</td>
<td align="right">0.21</td>
<td align="right">-0.04</td>
</tr>
<tr class="odd">
<td align="left">k_srq_admiration</td>
<td align="left">~~</td>
<td align="left">k_srq_sexual_relationships</td>
<td align="left">0.58 [ 0.30, 0.87]</td>
<td align="left">0.69 [ 0.09, 1.29]</td>
<td align="right">0.66</td>
<td align="right">0.80</td>
</tr>
<tr class="even">
<td align="left">k_srq_admiration</td>
<td align="left">~~</td>
<td align="left">k_srq_sociability</td>
<td align="left">0.62 [ 0.35, 0.90]</td>
<td align="left">0.86 [ 0.25, 1.48]</td>
<td align="right">0.80</td>
<td align="right">0.87</td>
</tr>
<tr class="odd">
<td align="left">k_srq_passivity</td>
<td align="left">~~</td>
<td align="left">k_srq_sexual_relationships</td>
<td align="left">0.09 [-0.11, 0.30]</td>
<td align="left">0.07 [-0.30, 0.43]</td>
<td align="right">0.08</td>
<td align="right">0.07</td>
</tr>
<tr class="even">
<td align="left">k_srq_passivity</td>
<td align="left">~~</td>
<td align="left">k_srq_sociability</td>
<td align="left">0.26 [ 0.05, 0.47]</td>
<td align="left">0.15 [-0.27, 0.58]</td>
<td align="right">0.27</td>
<td align="right">0.14</td>
</tr>
<tr class="odd">
<td align="left">k_srq_sexual_relationships</td>
<td align="left">~~</td>
<td align="left">k_srq_sociability</td>
<td align="left">0.62 [ 0.27, 0.98]</td>
<td align="left">0.72 [ 0.11, 1.34]</td>
<td align="right">0.80</td>
<td align="right">1.06</td>
</tr>
</tbody>
</table>
<div class="figure">
<span id="fig:unnamed-chunk-11"></span>
<img src="fsmi-cfa_files/figure-html/unnamed-chunk-11-1.png" alt="Correlations between FSMI and K-SRQ scales of interest." width="456"><p class="caption">
Figure 6: Correlations between FSMI and K-SRQ scales of interest.
</p>
</div>
<div id="k-srq-discussion" class="section level3">
<h3 class="hasAnchor">
<a href="#k-srq-discussion" class="anchor"></a>K-SRQ Discussion</h3>
<p>A CFA for four of the K-SRQ factors (admiration, passivity, sexual relationships, and sociability) fit fairly well (RMSEA = 0.064, <span class="math inline">\(\hat\gamma\)</span> = 0.964).
All factors except passivity were strongly inter-correlated, raising doubts about the discriminant validity of the separate factors.
A parallel scree plot analysis suggests a 3 factor structure, with one item from the original sociability factor loading on a factor with the admiration items (weakly), and the other two loading with the sexual relationships items.
A CFA using this factor structure (with no cross-loadings) demonstrates similar fit to the <em>a priori</em> model (RMSEA = 0.064, <span class="math inline">\(\hat\gamma\)</span> = 0.964), and with similarly substantial correlations between the former admiration and sexual relationships factors.
A 4 factor EFA retains this general structure, while letting the sociability item, which previously loaded with admiration items, dominate its own factor.
The new 3-factor structure improves somewhat on the <em>a priori</em> model, but the sexual relationships factor has not become any more interpretable as representing a mate-seeking motivation, per se.
Moreover, the sexual relationship factor, as well as its cousin in the 3-factor model both show nominally higher correlations with FSMI status than FSMI mate-seeking.
I use the <em>a priori</em> scale throughout.</p>
<p>The items on the FSMI mate-seeking scale ask almost exlusively aboout seaching for a <em>new</em> romantic or sexula partner, while the K-SRQ sexual relationship scale asks about enjoyment of socio-sexual interaction (e.g., kissing, flirting).
One would expect that the FSMI mate-seeking and K-SRQ sexual relationship correlation would be different between those who are in long term relationships and those who are not.
There is, in fact, a notable difference in the sign of this correlation between people who report being in a long-term relationship than people how report dating, or being single and not dating.
In a model where factor loadings have been constrained across group <span class="citation">(with minimal difference in fit statistics which is necessary for comparison of factor covariances; <span class="math inline">\(\delta\)</span>RMSEA = -0.00003, <span class="math inline">\(\delta\)</span>MFI = -0.012, <span class="math inline">\(\delta\hat{\gamma}\)</span> = -0.003; <span class="citeproc-not-found" data-reference-id="gregorich2006"><strong>???</strong></span>)</span>, people who are in a long term relationship show a negative correlation between FSMI mate-seeking K-SRQ sexual relationships (Table <a href="#fig:ksqrmatestatcor"><strong>??</strong></a>.
For people who are not in long-term relationships, there is a positive, significant, correlation between FSMI mate-seeking and the K-SRQ sexual relationships factor.
The relation between FSMI status and this same factor is, however, nominally higher regardless of long-term relationship status.</p>
<p>The K-SRQ admiration-derived factor showed reasonably high correlation with FSMI status, although this was not dissimiler in magnitude from the correlation it shows with the K-SRQ sexual relationship factor.</p>
<p>Generally, the three K-SRQ subscales of interest (but not the passivity subscale) all correlate rather highly among themselves. All four K-SRQ subscales (inlcuding passivity) tend to medium to small correlations with FSMI mate-seeking among people not in long-term relationships, and small or negative correlations among those not in long-term relationships. Across both groups, FSMI status shows medium to large correlations to the K-SRQ subscales except for passivity.</p>
<p>Given how differently the K-SRQ sexual relationships factor covaries with other relevant contructs and across groups, it is clear that it is measuring something distinctly from what the FSMI mate seeking factor is measuring.
The distinction between the seeking new romantic or sexual partners, and enjoyment of engaging in socio-sexual behavior may be important when examining how these motivational factors relate to risk-taking.
Past work has shown that sexual activity (age at first sex, specifically), if it is in the context of a romantic relationshuip, is protective with respect to dellinquency <span class="citation">(Harden &amp; Mendle, 2011; Harden, Mendle, Hill, Turkheimer, &amp; Emery, 2007)</span>.</p>
</div>
</div>
</div>
<div id="predicting-sexual-behavior" class="section level1">
<h1 class="hasAnchor">
<a href="#predicting-sexual-behavior" class="anchor"></a>Predicting sexual behavior</h1>
<p>The number of partners and frequency of sex is expected to be different between those who are in or not in long-term relationships.</p>
<p><img src="fsmi-cfa_files/figure-html/sesfsmiplot-1.png" width="768"></p>
<table class="table">
<thead><tr class="header">
<th align="left">lhs</th>
<th align="left">op</th>
<th align="left">rhs</th>
<th align="right">est</th>
<th align="right">se</th>
<th align="right">z</th>
<th align="right">pvalue</th>
<th align="right">ci.lower</th>
<th align="right">ci.upper</th>
<th align="right">std.lv</th>
<th align="right">std.all</th>
<th align="right">std.nox</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">ordered_num_partner</td>
<td align="left">~</td>
<td align="left">fsmi_mate</td>
<td align="right">0.24</td>
<td align="right">0.07</td>
<td align="right">3.30</td>
<td align="right">0.00</td>
<td align="right">0.10</td>
<td align="right">0.38</td>
<td align="right">0.29</td>
<td align="right">0.28</td>
<td align="right">0.28</td>
</tr>
<tr class="even">
<td align="left">ordered_num_partner</td>
<td align="left">~</td>
<td align="left">gender_c</td>
<td align="right">-0.46</td>
<td align="right">0.18</td>
<td align="right">-2.54</td>
<td align="right">0.01</td>
<td align="right">-0.82</td>
<td align="right">-0.11</td>
<td align="right">-0.46</td>
<td align="right">-0.21</td>
<td align="right">-0.45</td>
</tr>
</tbody>
</table>
<table class="table">
<thead><tr class="header">
<th align="left">lhs</th>
<th align="left">op</th>
<th align="left">rhs</th>
<th align="right">est</th>
<th align="right">se</th>
<th align="right">z</th>
<th align="right">pvalue</th>
<th align="right">ci.lower</th>
<th align="right">ci.upper</th>
<th align="right">std.lv</th>
<th align="right">std.all</th>
<th align="right">std.nox</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">ordered_num_partner</td>
<td align="left">~</td>
<td align="left">k_srq_sexual_relationships</td>
<td align="right">0.31</td>
<td align="right">0.09</td>
<td align="right">3.61</td>
<td align="right">0.00</td>
<td align="right">0.14</td>
<td align="right">0.49</td>
<td align="right">0.35</td>
<td align="right">0.34</td>
<td align="right">0.34</td>
</tr>
<tr class="even">
<td align="left">ordered_num_partner</td>
<td align="left">~</td>
<td align="left">gender_c</td>
<td align="right">-0.40</td>
<td align="right">0.19</td>
<td align="right">-2.12</td>
<td align="right">0.03</td>
<td align="right">-0.77</td>
<td align="right">-0.03</td>
<td align="right">-0.40</td>
<td align="right">-0.18</td>
<td align="right">-0.39</td>
</tr>
</tbody>
</table>
<table class="table">
<thead><tr class="header">
<th align="left">lhs</th>
<th align="left">op</th>
<th align="left">rhs</th>
<th align="right">block</th>
<th align="right">group</th>
<th align="right">est</th>
<th align="right">se</th>
<th align="right">z</th>
<th align="right">pvalue</th>
<th align="right">ci.lower</th>
<th align="right">ci.upper</th>
<th align="right">std.lv</th>
<th align="right">std.all</th>
<th align="right">std.nox</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">ordered_sex_freq</td>
<td align="left">~</td>
<td align="left">fsmi_mate</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">-0.05</td>
<td align="right">0.07</td>
<td align="right">-0.72</td>
<td align="right">0.47</td>
<td align="right">-0.18</td>
<td align="right">0.08</td>
<td align="right">-0.06</td>
<td align="right">-0.06</td>
<td align="right">-0.06</td>
</tr>
<tr class="even">
<td align="left">ordered_sex_freq</td>
<td align="left">~</td>
<td align="left">gender_c</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">-0.42</td>
<td align="right">0.19</td>
<td align="right">-2.15</td>
<td align="right">0.03</td>
<td align="right">-0.80</td>
<td align="right">-0.04</td>
<td align="right">-0.42</td>
<td align="right">-0.19</td>
<td align="right">-0.41</td>
</tr>
<tr class="odd">
<td align="left">ordered_sex_freq</td>
<td align="left">~</td>
<td align="left">fsmi_mate</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">-0.09</td>
<td align="right">0.13</td>
<td align="right">-0.69</td>
<td align="right">0.49</td>
<td align="right">-0.35</td>
<td align="right">0.17</td>
<td align="right">-0.10</td>
<td align="right">-0.10</td>
<td align="right">-0.10</td>
</tr>
<tr class="even">
<td align="left">ordered_sex_freq</td>
<td align="left">~</td>
<td align="left">gender_c</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">0.06</td>
<td align="right">0.35</td>
<td align="right">0.16</td>
<td align="right">0.87</td>
<td align="right">-0.62</td>
<td align="right">0.73</td>
<td align="right">0.06</td>
<td align="right">0.03</td>
<td align="right">0.06</td>
</tr>
</tbody>
</table>
<table class="table">
<thead><tr class="header">
<th align="left">lhs</th>
<th align="left">op</th>
<th align="left">rhs</th>
<th align="right">block</th>
<th align="right">group</th>
<th align="right">est</th>
<th align="right">se</th>
<th align="right">z</th>
<th align="right">pvalue</th>
<th align="right">ci.lower</th>
<th align="right">ci.upper</th>
<th align="right">std.lv</th>
<th align="right">std.all</th>
<th align="right">std.nox</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">ordered_sex_freq</td>
<td align="left">~</td>
<td align="left">k_srq_sexual_relationships</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0.24</td>
<td align="right">0.08</td>
<td align="right">2.90</td>
<td align="right">0.00</td>
<td align="right">0.08</td>
<td align="right">0.40</td>
<td align="right">0.27</td>
<td align="right">0.26</td>
<td align="right">0.26</td>
</tr>
<tr class="even">
<td align="left">ordered_sex_freq</td>
<td align="left">~</td>
<td align="left">gender_c</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">-0.26</td>
<td align="right">0.20</td>
<td align="right">-1.29</td>
<td align="right">0.20</td>
<td align="right">-0.66</td>
<td align="right">0.13</td>
<td align="right">-0.26</td>
<td align="right">-0.12</td>
<td align="right">-0.26</td>
</tr>
<tr class="odd">
<td align="left">ordered_sex_freq</td>
<td align="left">~</td>
<td align="left">k_srq_sexual_relationships</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">0.23</td>
<td align="right">0.19</td>
<td align="right">1.20</td>
<td align="right">0.23</td>
<td align="right">-0.14</td>
<td align="right">0.59</td>
<td align="right">0.14</td>
<td align="right">0.14</td>
<td align="right">0.14</td>
</tr>
<tr class="even">
<td align="left">ordered_sex_freq</td>
<td align="left">~</td>
<td align="left">gender_c</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">0.06</td>
<td align="right">0.35</td>
<td align="right">0.17</td>
<td align="right">0.86</td>
<td align="right">-0.63</td>
<td align="right">0.76</td>
<td align="right">0.06</td>
<td align="right">0.03</td>
<td align="right">0.06</td>
</tr>
</tbody>
</table>
<table class="table">
<thead><tr class="header">
<th align="left">lhs</th>
<th align="left">op</th>
<th align="left">rhs</th>
<th align="right">est</th>
<th align="right">se</th>
<th align="right">z</th>
<th align="right">pvalue</th>
<th align="right">ci.lower</th>
<th align="right">ci.upper</th>
<th align="right">std.lv</th>
<th align="right">std.all</th>
<th align="right">std.nox</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">ordered_num_partner</td>
<td align="left">~</td>
<td align="left">fsmi_mate</td>
<td align="right">0.15</td>
<td align="right">0.08</td>
<td align="right">1.87</td>
<td align="right">0.06</td>
<td align="right">-0.01</td>
<td align="right">0.30</td>
<td align="right">0.19</td>
<td align="right">0.19</td>
<td align="right">0.19</td>
</tr>
<tr class="even">
<td align="left">ordered_num_partner</td>
<td align="left">~</td>
<td align="left">k_srq_sexual_relationships</td>
<td align="right">0.26</td>
<td align="right">0.10</td>
<td align="right">2.56</td>
<td align="right">0.01</td>
<td align="right">0.06</td>
<td align="right">0.45</td>
<td align="right">0.29</td>
<td align="right">0.28</td>
<td align="right">0.28</td>
</tr>
<tr class="odd">
<td align="left">ordered_num_partner</td>
<td align="left">~</td>
<td align="left">gender_c</td>
<td align="right">-0.38</td>
<td align="right">0.20</td>
<td align="right">-1.91</td>
<td align="right">0.06</td>
<td align="right">-0.77</td>
<td align="right">0.01</td>
<td align="right">-0.38</td>
<td align="right">-0.17</td>
<td align="right">-0.37</td>
</tr>
</tbody>
</table>
<table class="table">
<thead><tr class="header">
<th align="left">lhs</th>
<th align="left">op</th>
<th align="left">rhs</th>
<th align="right">block</th>
<th align="right">group</th>
<th align="right">est</th>
<th align="right">se</th>
<th align="right">z</th>
<th align="right">pvalue</th>
<th align="right">ci.lower</th>
<th align="right">ci.upper</th>
<th align="right">std.lv</th>
<th align="right">std.all</th>
<th align="right">std.nox</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="left">ordered_sex_freq</td>
<td align="left">~</td>
<td align="left">fsmi_mate</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">-0.19</td>
<td align="right">0.08</td>
<td align="right">-2.40</td>
<td align="right">0.02</td>
<td align="right">-0.35</td>
<td align="right">-0.03</td>
<td align="right">-0.24</td>
<td align="right">-0.24</td>
<td align="right">-0.24</td>
</tr>
<tr class="even">
<td align="left">ordered_sex_freq</td>
<td align="left">~</td>
<td align="left">k_srq_sexual_relationships</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">0.33</td>
<td align="right">0.10</td>
<td align="right">3.35</td>
<td align="right">0.00</td>
<td align="right">0.14</td>
<td align="right">0.53</td>
<td align="right">0.39</td>
<td align="right">0.38</td>
<td align="right">0.38</td>
</tr>
<tr class="odd">
<td align="left">ordered_sex_freq</td>
<td align="left">~</td>
<td align="left">gender_c</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right">-0.32</td>
<td align="right">0.21</td>
<td align="right">-1.54</td>
<td align="right">0.12</td>
<td align="right">-0.74</td>
<td align="right">0.09</td>
<td align="right">-0.32</td>
<td align="right">-0.15</td>
<td align="right">-0.32</td>
</tr>
<tr class="even">
<td align="left">ordered_sex_freq</td>
<td align="left">~</td>
<td align="left">fsmi_mate</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">-0.11</td>
<td align="right">0.18</td>
<td align="right">-0.59</td>
<td align="right">0.56</td>
<td align="right">-0.46</td>
<td align="right">0.25</td>
<td align="right">-0.11</td>
<td align="right">-0.11</td>
<td align="right">-0.11</td>
</tr>
<tr class="odd">
<td align="left">ordered_sex_freq</td>
<td align="left">~</td>
<td align="left">k_srq_sexual_relationships</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">0.19</td>
<td align="right">0.28</td>
<td align="right">0.69</td>
<td align="right">0.49</td>
<td align="right">-0.35</td>
<td align="right">0.73</td>
<td align="right">0.11</td>
<td align="right">0.11</td>
<td align="right">0.11</td>
</tr>
<tr class="even">
<td align="left">ordered_sex_freq</td>
<td align="left">~</td>
<td align="left">gender_c</td>
<td align="right">2</td>
<td align="right">2</td>
<td align="right">0.00</td>
<td align="right">0.35</td>
<td align="right">0.00</td>
<td align="right">1.00</td>
<td align="right">-0.69</td>
<td align="right">0.69</td>
<td align="right">0.00</td>
<td align="right">0.00</td>
<td align="right">0.00</td>
</tr>
</tbody>
</table>
<p>FSMI mate-seeking and KSRQ sexual relationships modified factor show interesting relations to sexual behavior. FSMI mate-seeking relates positively to number of sexual partners (for people not in long-term relationships). KSRQ sexual relationships relates to number of sexual experiences for people not in long-term relationships. <strong>Need to test constraining relation between partnered and non-partnered people. Need to examine KSRQ and mate-seeking in the same model.</strong></p>
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h1>
<div id="refs" class="references">
<div id="ref-harden2011a">
<p>Harden, K. P., &amp; Mendle, J. (2011). Adolescent Sexual Activity and the Development of Delinquent Behavior: The Role of Relationship Context. <em>Journal of Youth and Adolescence</em>, <em>40</em>(7), 825–838. doi:<a href="https://doi.org/10.1007/s10964-010-9601-y">10.1007/s10964-010-9601-y</a></p>
</div>
<div id="ref-harden2007">
<p>Harden, K. P., Mendle, J., Hill, J. E., Turkheimer, E., &amp; Emery, R. E. (2007). Rethinking Timing of First Sex and Delinquency. <em>Journal of Youth and Adolescence</em>, <em>37</em>(4), 373–385. doi:<a href="https://doi.org/10.1007/s10964-007-9228-9">10.1007/s10964-007-9228-9</a></p>
</div>
<div id="ref-neel2015">
<p>Neel, R., Kenrick, D. T., White, A. E., &amp; Neuberg, S. L. (2015). Individual Differences in Fundamental Social Motives. <em>Journal of Personality and Social Psychology</em>, No Pagination Specified. doi:<a href="https://doi.org/10.1037/pspp0000068">10.1037/pspp0000068</a></p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li>
<a href="#checking-items">Checking Items</a><ul class="nav nav-pills nav-stacked">
<li><a href="#fsmi">FSMI</a></li>
      <li><a href="#dominance-and-prestige">Dominance and Prestige</a></li>
      <li><a href="#kids-social-reward-questionnaire">Kids social reward questionnaire</a></li>
      <li><a href="#social-achievement-goals">Social achievement goals</a></li>
      <li><a href="#urgency-premeditation-perseverance-and-sensation-seeking">Urgency, Premeditation, Perseverance, and Sensation Seeking</a></li>
      </ul>
</li>
      <li>
<a href="#confirmatory-factor-analyses-and-exploration">Confirmatory factor analyses and exploration</a><ul class="nav nav-pills nav-stacked">
<li>
<a href="#fsmi-1">FSMI</a><ul class="nav nav-pills nav-stacked">
<li><a href="#fsmi-discussion">FSMI Discussion</a></li>
      </ul>
</li>
      <li>
<a href="#k-srq">K-SRQ</a><ul class="nav nav-pills nav-stacked">
<li><a href="#k-srq-discussion">K-SRQ Discussion</a></li>
      </ul>
</li>
      </ul>
</li>
      <li><a href="#predicting-sexual-behavior">Predicting sexual behavior</a></li>
      <li><a href="#references">References</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by John Flournoy.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://pkgdown.r-lib.org/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  

  </body>
</html>
