<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Test Simulated Data • probly</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js" integrity="sha384-cV+rhyOuRHc9Ub/91rihWcGmMmCXDeksTtCihMupQHSsi8GIIRDG0ThDc3HGQFJ3" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../jquery.sticky-kit.min.js"></script><script src="../pkgdown.js"></script><meta property="og:title" content="Test Simulated Data">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-vignette">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">probly</a>
        <span class="label label-default" data-toggle="tooltip" data-placement="bottom" title="Released package">0.1.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/age-and-puberty-data.html">Age, Puberty, and Informant Data</a>
    </li>
    <li>
      <a href="../articles/collect-data.html">Collect and Clean SPLT Data</a>
    </li>
    <li>
      <a href="../articles/descriptive-statistics.html">Descriptive Statistics for SPLT data</a>
    </li>
    <li>
      <a href="../articles/fit-model-to-participant-data.html">Fit model to participant data</a>
    </li>
    <li>
      <a href="../articles/test-simple-3l-mv-model.html">Test Simple 3-level Multivariate Normal Model</a>
    </li>
    <li>
      <a href="../articles/test-simulated-data.html">Test Simulated Data</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9">
    <div class="page-header toc-ignore">
      <h1>Test Simulated Data</h1>
                        <h4 class="author">John Flournoy</h4>
            
            <h4 class="date">2018-04-06</h4>
      
      

    </div>

    
    
<div class="contents">
<p><strong>Aim 1a:</strong> Does framing reinforcement learning with (mate-seeking and status) motivational contexts sensitize the learner and potentiate learning?</p>
<p>My approach to answering this question is to model how learning occurs in each of the three motive contexts and examine differences in how learning occurs.</p>
<div id="a-model-for-reinforcement-learning" class="section level1">
<h1 class="hasAnchor">
<a href="#a-model-for-reinforcement-learning" class="anchor"></a>A model for reinforcement learning</h1>
<p>In the context of this task, where the relation between the optimal response and the stimulus is constant, a simple model of the degree of learning could rely on a simple proportion of optimal responses <span class="math inline">\(P_{ok}\)</span> for each condition <span class="math inline">\(k\)</span>. The test of the hypothesis of the effect of framing would then be the difference between conditions in <span class="math inline">\(P_o\)</span>. This simple model sacrifice precision for simplicity, and so I will be modeling the data using a reinforcement learning model with several parameters that can account for deviations from a strict Rescorla-Wagner (RW) process. This increases the number of possible comparisons I am able to make between conditions, which may generate useful information about how motive-domain framing affects the learning process (as modeled, of course), but which also increases the complexity of patterns between conditions and parameters that must be interpreted. It will be helpful to keep in mind that the framing can only be said to potentiate learning if, regardless of its affect on any model parameters, it does not result in higher proportions of optimal responding.</p>
<p>In this section, I simulate data as expected under the Rescorla-Wagner model implemented by <span class="citation">Ahn, Haines, &amp; Zhang (2017)</span> in their go-no-go model 2. Their original model handles binary decisions (button-press or no button-press) in response to four different cues. However, the form of the learning algorithm is generalizable to other binary choices in response to cues. In the case of the Social Probabilistic Learning Task (SPLT), participants are presented with a face (the cue), and must decide to press the left key or the right key. They are rewarded probabilistically such that for each cue, one or the other of the response options has an 80% chance of providing reinforcement. The go-no-go models used by <span class="citation">Ahn et al. (2017)</span> were derived from work by <span class="citation">Guitart-Masip et al. (2012)</span>. Their most flexible reinforcement learning model generates the probability of an action for each trial via N parameters: the learning rate, <span class="math inline">\(\epsilon\)</span>, the effective size of reinforcement, <span class="math inline">\(\rho\)</span>, a static bias parameter, <span class="math inline">\(b\)</span>, an irreducible noise parameter, <span class="math inline">\(\xi\)</span>, and a Pavlovian learning parameter, <span class="math inline">\(\pi\)</span>. In the SPLT, trial feedback does not vary by valence (responses result in reward, or no reward, but never punishment), so I use the model that does not include this Pavlovian component.</p>
</div>
<div id="reinforcement-learning-model-for-the-splt" class="section level1">
<h1 class="hasAnchor">
<a href="#reinforcement-learning-model-for-the-splt" class="anchor"></a>Reinforcement learning model for the SPLT</h1>
<p>The model for an individual <span class="math inline">\(j\)</span>’s probability of pressing the right arrow key on trial <span class="math inline">\(t\)</span> given that stimulus <span class="math inline">\(s_{t}\)</span> is presented, <span class="math inline">\(P(a_{\rightarrow t} | s_{t})_{t}\)</span>, is determined by a logistic transformation of the action weight for pressing the right arrow key minus the action weight for pressing the left arrow key. This probability is then adjusted by a noise parameter, <span class="math inline">\(0 \leq\xi_{jk}\leq1\)</span> for each participant <span class="math inline">\(j\)</span> in condition <span class="math inline">\(k\)</span>. The noise parameter modulates the degree to which responses are non-systematic. When <span class="math inline">\(\xi\)</span> is 1, <span class="math inline">\(P_{it} = .5\)</span>, and because each individual has a unique noise parameter for each condition, I am able to account for participants who do not learn during the task, or in a particular condition. The full equation is:</p>
<p><span class="math display">\[
P(a_{\rightarrow t} | s_{t})_{t} = 
\text{logit}^{-1}\big(W(a_{\rightarrow t}| s_{t}) - W(a_{\leftarrow t}| s_{t})\big)\cdot(1-\xi_{jk}) + \small\frac{\xi_{jk}}{2}.
\]</span></p>
<p>The action weight is determined by a Rescorla-Wagner (RW) updating equation and individual <span class="math inline">\(j\)</span>’s bias parameter, <span class="math inline">\(b_{jk}\)</span>, for that condition (which encodes a systematic preference for choosing the left or right response option). In each condition, the same two words are displayed in the same position, so <span class="math inline">\(b\)</span> encodes a learning-independent preference for one particular word or position. The equation for the action weight for each action on a particular trial is:</p>
<p><span class="math display">\[
W_{t}(a,s) = \left\{
                \begin{array}{ll}
                  Q_{t}(a, s) + b_{jk}, &amp; \text{if } a=a_{\rightarrow} \\
                  Q_{t}(a, s), &amp; \text{otherwise}
                \end{array}
              \right.
\]</span> Finally, the RW updating equation that encodes instrumental learning is governed by the individual’s learning rate for that condition, <span class="math inline">\(\epsilon_{jk}\)</span>, and a scaling parameter <span class="math inline">\(\rho_{jk}\)</span> governing the effective size of the possible rewards <span class="math inline">\(r_t \in \{0, 1, 5\}\)</span>:</p>
<p><span class="math display">\[
Q_{t}(a_t, s_t) = Q_{t-1}(a_t, s_t) + \epsilon_{jk}\big(\rho_{jk}r_t - Q_{t-1}(a_t, s_t)\big)
\]</span></p>
<div id="hierarchical-parameters" class="section level2">
<h2 class="hasAnchor">
<a href="#hierarchical-parameters" class="anchor"></a>Hierarchical Parameters</h2>
<p>Each parameter (<span class="math inline">\(\epsilon, \rho, b, \xi\)</span>) varies by condition <span class="math inline">\(k \in 1:K\)</span>, and by participant <span class="math inline">\(j \in 1:J\)</span> nested in sample <span class="math inline">\(m \in 1:M\)</span>. The structure of the hierarchical part of the model is the same for each parameter, so the following description for <span class="math inline">\(\epsilon\)</span> will serve as a description for all of the parameters. For each individual <span class="math inline">\(j\)</span>, <span class="math inline">\(\beta_{\epsilon j}\)</span> is a <span class="math inline">\(K\)</span>-element row of coefficients for parameter <span class="math inline">\(\epsilon\)</span> for each condition:</p>
<p><span class="math display">\[
\beta_{\epsilon j} \sim \mathcal{N}(\delta_{\epsilon mm[j]}, \Sigma_{\epsilon})
\]</span> where <span class="math inline">\(\delta_{\epsilon mm[j]}\)</span> is a column of <span class="math inline">\(K\)</span> means for individual <span class="math inline">\(j\)</span>’s sample <span class="math inline">\(M\)</span>, as indexed in the vector <span class="math inline">\(mm\)</span>, and <span class="math inline">\(\Sigma_{\epsilon}\)</span> is a <span class="math inline">\(K\times K\)</span> matrix of the covariance of individual coefficients between conditions.</p>
<p>Finally, across all <span class="math inline">\(M\)</span> samples, the means for each condition k are distributed such that:</p>
<p><span class="math display">\[
\delta_{\epsilon k} \sim \mathcal{N}(\mu_{\epsilon k}, \sigma_\epsilon)
\]</span></p>
<p>where <span class="math inline">\(\mu_{\epsilon k}\)</span> is the population mean for parameter <span class="math inline">\(\epsilon\)</span> in condition <span class="math inline">\(k\)</span>, and <span class="math inline">\(\sigma\)</span> is a slightly regularizing scale parameter for these means across all conditions and samples. The priors for these final parameters are:</p>
<p><span class="math display">\[
\mu_\epsilon \sim \mathcal{N}(0, 5)\\
\sigma_\epsilon \sim \text{exponential(1)}.
\]</span></p>
</div>
</div>
<div id="simulating-data" class="section level1">
<h1 class="hasAnchor">
<a href="#simulating-data" class="anchor"></a>Simulating data</h1>
<p>Before modeling the task data, I will confirm that this model can recover known parameters from simulated data. I simulate data based on the structure of the sample data, using the same number of participants per sample (see the section on <a href="descriptive-statistics.html">descriptive statistics</a>, as well as precisely the same task structure. For this aim, it is important to be able to recover all <span class="math inline">\(\mu_{\theta k}\)</span> for <span class="math inline">\(\theta \in \{\epsilon,\rho,b,\xi\}\)</span> and <span class="math inline">\(k \in \{1,2,3\}\)</span>, where 1 = Hungry/Thirsty, 2 = Popular/Unpopular, and 3 = Dating/Looking. Those parameters that account for idiosyncratic deviation from RW-expected behavior (<span class="math inline">\(b,\xi\)</span>) will not vary by condition. Based on interactive simulation (<a href="https://jflournoy.shinyapps.io/rw_model/">here</a>), reasonable parameter values for the control condition might be <span class="math inline">\(\mu_\epsilon = -1.65\)</span> and <span class="math inline">\(\mu_\rho = -0.3\)</span>.<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a></p>
<p>The <a href="http://github.com/jflournoy/probly"><code>probly</code></a> package contains functions that help generate sample- and individually-varying coefficients for parameters, as well as simulated data from task structure.</p>
<p>One early indication that a model may not be well suited to a particular data set is that the model, given reasonable parameter values, is not able to produce simulated data that looks like the real data one is attempting to model. The simulated data do generally behave similarly to the actual data when we look just at the proportion of optimal presses over time (Figure <a href="#fig:simdata">1</a> and Figure <a href="#fig:simdatasample">2</a>, below, and Figure X in the section on <a href="http://127.0.0.1:9740/rmd_output/4/descriptive-statistics.html">descriptive statistics</a>).</p>
<div class="figure">
<span id="fig:simdata"></span>
<img src="test-simulated-data_files/figure-html/simdata-1.png" alt="Simulated task data. This shows the the proportion of optimal presses across all participants for each trial. The best-fit line is a generalized additive model and is only intended for illustrative purposes." width="576"><p class="caption">
Figure 1: Simulated task data. This shows the the proportion of optimal presses across all participants for each trial. The best-fit line is a generalized additive model and is only intended for illustrative purposes.
</p>
</div>

<div class="figure">
<span id="fig:simdatasample"></span>
<img src="test-simulated-data_files/figure-html/simdatasample-1.png" alt="Simulated task data for each sample." width="576"><p class="caption">
Figure 2: Simulated task data for each sample.
</p>
</div>

</div>
<div id="recovery-of-population-parameters" class="section level1">
<h1 class="hasAnchor">
<a href="#recovery-of-population-parameters" class="anchor"></a>Recovery of population parameters</h1>
<p>The model as described above was fit to simulated data using RStan <span class="citation">(version 2.17.3; Stan Development Team, 2018)</span>, sampling from 4 chains with 1000 warmup iterations and 500 sampling iterations per chain. The posterior means for each parameter are compared to those that generated the simulated task behavior. The plots in Figure <a href="#fig:musimfitplot">3</a> allow visual comparison of the fitted model posteriors for each parameter to the data-generating population means, as well as to the means of the data-generating parameters for each sample, and for each individual. It is clear from these plots that the parameter estimates from this particular run capture the generating parameters, with two exceptions. First, the estimate of the population mean of the irrudicble noise parameter, <span class="math inline">\(\xi\)</span>, for one condition did not capture the generating parameter. This may be because this parameter was intentionally set very low so that <span class="math inline">\(\xi^\prime \approx 0\)</span>. The second instance occurs with the bias parameter for one condition. This may be acceptable because the parameters of interest safely capture the generating values, and this single condition bias parameter is not very far from the identity line. Additionally, it should be noted that the fitted model does capture the mean of generating <span class="math inline">\(\delta_b\)</span> and <span class="math inline">\(\beta_b\)</span> parameters for all conditions.</p>
<div class="figure">
<span id="fig:musimfitplot"></span>
<img src="test-simulated-data_files/figure-html/musimfitplot-1.png" alt="Comparison of model fit to generating parameters. Gray bars are 95% credible intervals. Black lines are identinty, where model fit and generating parameters are exactly equal." width="768"><p class="caption">
Figure 3: Comparison of model fit to generating parameters. Gray bars are 95% credible intervals. Black lines are identinty, where model fit and generating parameters are exactly equal.
</p>
</div>

<div id="simulating-more-iterations" class="section level2">
<h2 class="hasAnchor">
<a href="#simulating-more-iterations" class="anchor"></a>Simulating more iterations</h2>
<p>Although the above results are promising, it is important to ensure that this is not a fluke. Unfortunately, it is apparent from running more models on other simulated data that many converge very slowly and all show post-warm-up divergent iterations.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(future)
<span class="kw">library</span>(future.batchtools)
<span class="kw">library</span>(probly)
<span class="kw">library</span>(listenv)

<span class="kw"><a href="http://www.rdocumentation.org/packages/future/topics/plan">plan</a></span>(batchtools_slurm,
     <span class="dt">template =</span> <span class="kw">system.file</span>(<span class="st">'batchtools'</span>, <span class="st">'batchtools.slurm.tmpl'</span>, <span class="dt">package =</span> <span class="st">'probly'</span>),
     <span class="dt">resources =</span> <span class="kw">list</span>(<span class="dt">ncpus =</span> <span class="dv">4</span>, <span class="dt">walltime =</span> <span class="dv">60</span>*<span class="dv">24</span>*<span class="dv">4</span>, <span class="dt">memory =</span> <span class="st">'1G'</span>,
                      <span class="dt">partitions =</span> <span class="st">'long,longfat'</span>))

data_dir &lt;-<span class="st"> '/home/flournoy/otherhome/data/splt/probly/'</span>
data_dir_indvsims &lt;-<span class="st"> </span><span class="kw">file.path</span>(data_dir, <span class="st">'indiv_sim_saves'</span>)
if(!<span class="kw">file.exists</span>(data_dir)){
    <span class="kw">stop</span>(<span class="st">'Data directory "'</span>, data_dir, <span class="st">'" does not exist'</span>)
} else {
    <span class="kw">message</span>(<span class="st">"Data goes here: "</span>, data_dir)
}
if(!<span class="kw">file.exists</span>(data_dir_indvsims)){
    <span class="kw">stop</span>(<span class="st">'Individual simulation directory "'</span>, data_dir_indvsims, <span class="st">'" does not exist'</span>)
} else {
    <span class="kw">message</span>(<span class="st">"Individual simulation results go here: "</span>, data_dir_indvsims)
}

<span class="kw">data</span>(splt)
splt_no_na &lt;-<span class="st"> </span>splt[!<span class="kw">is.na</span>(splt$pressed_r), ]
splt_no_na$proportion_fac &lt;-<span class="st"> </span><span class="kw">factor</span>(splt_no_na$proportion, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">'80_20'</span>, <span class="st">'20_80'</span>))
optimal_side_mat &lt;-<span class="st"> </span><span class="kw"><a href="../reference/get_col_as_trial_matrix.html">get_col_as_trial_matrix</a></span>(splt_no_na, <span class="dt">col =</span> <span class="st">'proportion_fac'</span>)

mu_xi &lt;-<span class="st"> </span><span class="kw">c</span>(-<span class="fl">2.7</span>, -<span class="fl">2.6</span>, -<span class="fl">2.4</span>)
mu_b &lt;-<span class="st"> </span><span class="kw">c</span>(-.<span class="dv">07</span>, .<span class="dv">28</span>, .<span class="dv">39</span>)
mu_eps &lt;-<span class="st"> </span><span class="kw">c</span>(-<span class="fl">1.65</span>, -<span class="fl">1.65</span> +<span class="st"> </span>.<span class="dv">3</span>, -<span class="fl">1.65</span> +<span class="st"> </span>.<span class="dv">2</span>)
mu_rho &lt;-<span class="st"> </span><span class="kw">c</span>(-.<span class="dv">3</span>, -.<span class="dv">3</span> +<span class="st"> </span>.<span class="dv">35</span>, -.<span class="dv">3</span> +<span class="st"> </span>.<span class="dv">45</span>)

task_structure &lt;-<span class="st"> </span>probly::<span class="kw"><a href="../reference/make_task_structure_from_data.html">make_task_structure_from_data</a></span>(splt_no_na)
task_structure_stan &lt;-<span class="st"> </span>task_structure <span class="co">#just to sub NA with -1</span>
task_structure_stan$condition[<span class="kw">is.na</span>(task_structure_stan$condition)] &lt;-<span class="st"> </span>-<span class="dv">1</span>
task_structure_stan$cue[<span class="kw">is.na</span>(task_structure_stan$cue)] &lt;-<span class="st"> </span>-<span class="dv">1</span>

stan_sim_data &lt;-<span class="st"> </span><span class="kw">list</span>(
    <span class="dt">N =</span> task_structure_stan$N,
    <span class="st">`</span><span class="dt">T</span><span class="st">`</span> =<span class="st"> </span><span class="kw">max</span>(task_structure_stan$Tsubj),
    <span class="dt">K =</span> task_structure_stan$K,
    <span class="dt">M =</span> task_structure_stan$M,
    <span class="dt">ncue =</span> task_structure_stan$n_cues,
    <span class="dt">mm =</span> task_structure_stan$mm,
    <span class="dt">Tsubj =</span> task_structure_stan$Tsubj,
    <span class="dt">condition =</span> task_structure_stan$condition,
    <span class="dt">cue =</span> task_structure_stan$cue
)

stan_rl_fn &lt;-<span class="st"> </span><span class="kw">system.file</span>(<span class="st">'stan'</span>, <span class="st">'splt_rl_reparam.stan'</span>, <span class="dt">package =</span> <span class="st">'probly'</span>)

iter &lt;-<span class="st"> </span><span class="dv">100</span>
results_f &lt;-<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/listenv/topics/listenv">listenv</a></span>()

for(i in <span class="dv">1</span>:iter){
    results_f[[i]] %&lt;-%<span class="st"> </span>{
        <span class="kw">library</span>(rstan)
        stan_sim_length &lt;-<span class="st"> </span><span class="kw">length</span>(stan_sim_data)
        task_data &lt;-<span class="st"> </span>probly::<span class="kw"><a href="../reference/simulate_splt_data.html">simulate_splt_data</a></span>(task_structure,
                                                <span class="dt">mu_xi =</span> mu_xi,
                                                <span class="dt">mu_b =</span> mu_b,
                                                <span class="dt">mu_eps =</span> mu_eps,
                                                <span class="dt">mu_rho =</span> mu_rho)
        task_data_stan &lt;-<span class="st"> </span>task_data$task_behavior
        task_data_stan$outcome_realized[<span class="kw">is.na</span>(task_data_stan$outcome_realized)] &lt;-<span class="st"> </span>-<span class="dv">1</span>
        task_data_stan$press_right[<span class="kw">is.na</span>(task_data_stan$press_right)] &lt;-<span class="st"> </span>-<span class="dv">1</span>

        stan_sim_data$press_right =<span class="st"> </span>task_data_stan$press_right
        stan_sim_data$outcome =<span class="st"> </span>task_data_stan$outcome

        trial_num &lt;-<span class="st"> </span>-(<span class="kw">dim</span>(optimal_side_mat)[<span class="dv">2</span>]-<span class="dv">1</span>):<span class="dv">0</span>
        prop_optimal_resp &lt;-<span class="st"> </span><span class="dv">100</span>*<span class="kw">apply</span>(
            task_data$task_behavior$press_right ==<span class="st"> </span>(optimal_side_mat -<span class="st"> </span><span class="dv">1</span>),
            <span class="dv">2</span>, mean, <span class="dt">na.rm =</span> T)
        learning_traj &lt;-<span class="st"> </span><span class="kw">coef</span>(<span class="kw">summary</span>(<span class="kw">lm</span>(prop_optimal_resp ~<span class="st"> </span>trial_num)))[,<span class="st">'Estimate'</span>]

        <span class="co"># ##--TESTING</span>
        <span class="co"># devtools::install_local('~/code_new/probly')</span>
        <span class="co"># stan_rl_fn &lt;- '~/code_new/probly/inst/stan/splt_rl_reparam.stan'</span>
        <span class="co"># stan_model_thing &lt;- rstan::stan_model(file = stan_rl_fn)</span>
        <span class="co"># stan_optim &lt;- rstan::optimizing(stan_model_thing, data = stan_sim_data)</span>
        <span class="co"># stan_optim_parnames &lt;- grep('mu', names(stan_optim$par), value = T)</span>
        <span class="co"># stan_optim$par[stan_optim_parnames] - c(mu_xi, mu_eps, mu_b, mu_rho)</span>
        <span class="co"># stan_vb &lt;- rstan::vb(stan_model_thing, data = stan_sim_data)</span>
        <span class="co"># summary(stan_vb, pars = stan_optim_parnames)</span>
        <span class="co"># ##--TESTING</span>

        stanFit &lt;-<span class="st"> </span>rstan::<span class="kw"><a href="http://www.rdocumentation.org/packages/rstan/topics/stan">stan</a></span>(<span class="dt">file =</span> stan_rl_fn,
                               <span class="dt">data =</span> stan_sim_data,
                               <span class="dt">chains =</span> <span class="dv">4</span>, <span class="dt">cores =</span> <span class="dv">4</span>,
                               <span class="dt">iter =</span> <span class="dv">1500</span>, <span class="dt">warmup =</span> <span class="dv">1000</span>,
                               <span class="dt">control =</span> <span class="kw">list</span>(<span class="dt">max_treedepth =</span> <span class="dv">15</span>, <span class="dt">adapt_delta =</span> <span class="fl">0.99</span>))

        model_summary &lt;-<span class="st"> </span>rstan::<span class="kw">summary</span>(stanFit)
        sampler_params &lt;-<span class="st"> </span>rstan::<span class="kw"><a href="http://www.rdocumentation.org/packages/rstan/topics/stanfit-class">get_sampler_params</a></span>(stanFit)

        return_list &lt;-<span class="st"> </span><span class="kw">list</span>(<span class="dt">fit_summary =</span> model_summary,
                            <span class="dt">sampler_params =</span> sampler_params,
                            <span class="dt">coefs =</span> learning_traj,
                            <span class="dt">data =</span> task_data)
        <span class="kw">saveRDS</span>(return_list, <span class="dt">file =</span> <span class="kw">file.path</span>(data_dir_indvsims,
                                              <span class="kw">paste0</span>(<span class="st">'sim_'</span>, <span class="kw">sprintf</span>(<span class="st">"%03d"</span>,i), <span class="st">'.RDS'</span>)))
        return_list
    }
}

results &lt;-<span class="st"> </span><span class="kw">as.list</span>(results_f)

<span class="kw">saveRDS</span>(results, <span class="kw">file.path</span>(data_dir, <span class="st">'test_rez.RDS'</span>))</code></pre></div>
<pre><code>#&gt; 
#&gt;   The decimal point is 1 digit(s) to the left of the |
#&gt; 
#&gt;     0 | 0000000000000000000000000000000000000000000000000000000000000
#&gt;     2 | 
#&gt;     4 | 
#&gt;     6 | 
#&gt;     8 | 
#&gt;    10 | 00000000000000000
#&gt;    12 | 
#&gt;    14 | 
#&gt;    16 | 
#&gt;    18 | 
#&gt;    20 | 000000000
#&gt;    22 | 
#&gt;    24 | 
#&gt;    26 | 
#&gt;    28 | 
#&gt;    30 | 0000000
#&gt;    32 | 
#&gt;    34 | 
#&gt;    36 | 
#&gt;    38 | 
#&gt;    40 | 0
#&gt;    42 | 
#&gt;    44 | 
#&gt;    46 | 
#&gt;    48 | 
#&gt;    50 | 
#&gt;    52 | 
#&gt;    54 | 
#&gt;    56 | 
#&gt;    58 | 
#&gt;    60 | 
#&gt;    62 | 
#&gt;    64 | 
#&gt;    66 | 
#&gt;    68 | 
#&gt;    70 | 
#&gt;    72 | 
#&gt;    74 | 
#&gt;    76 | 
#&gt;    78 | 
#&gt;    80 | 
#&gt;    82 | 
#&gt;    84 | 
#&gt;    86 | 
#&gt;    88 | 
#&gt;    90 | 0
#&gt;    92 | 
#&gt;    94 | 
#&gt;    96 | 
#&gt;    98 | 
#&gt;   100 | 
#&gt;   102 | 
#&gt;   104 | 
#&gt;   106 | 
#&gt;   108 | 
#&gt;   110 | 0
#&gt;   112 | 
#&gt;   114 | 
#&gt;   116 | 
#&gt;   118 | 
#&gt;   120 | 
#&gt;   122 | 
#&gt;   124 | 
#&gt;   126 | 
#&gt;   128 | 
#&gt;   130 | 
#&gt;   132 | 
#&gt;   134 | 
#&gt;   136 | 
#&gt;   138 | 
#&gt;   140 | 
#&gt;   142 | 
#&gt;   144 | 
#&gt;   146 | 
#&gt;   148 | 
#&gt;   150 | 
#&gt;   152 | 
#&gt;   154 | 
#&gt;   156 | 
#&gt;   158 | 
#&gt;   160 | 
#&gt;   162 | 
#&gt;   164 | 
#&gt;   166 | 
#&gt;   168 | 
#&gt;   170 | 
#&gt;   172 | 
#&gt;   174 | 
#&gt;   176 | 
#&gt;   178 | 
#&gt;   180 | 
#&gt;   182 | 
#&gt;   184 | 
#&gt;   186 | 
#&gt;   188 | 
#&gt;   190 | 
#&gt;   192 | 
#&gt;   194 | 
#&gt;   196 | 
#&gt;   198 | 
#&gt;   200 | 
#&gt;   202 | 
#&gt;   204 | 
#&gt;   206 | 
#&gt;   208 | 
#&gt;   210 | 
#&gt;   212 | 
#&gt;   214 | 
#&gt;   216 | 
#&gt;   218 | 
#&gt;   220 | 
#&gt;   222 | 
#&gt;   224 | 
#&gt;   226 | 
#&gt;   228 | 
#&gt;   230 | 
#&gt;   232 | 
#&gt;   234 | 
#&gt;   236 | 
#&gt;   238 | 
#&gt;   240 | 
#&gt;   242 | 
#&gt;   244 | 
#&gt;   246 | 
#&gt;   248 | 
#&gt;   250 | 
#&gt;   252 | 
#&gt;   254 | 
#&gt;   256 | 
#&gt;   258 | 
#&gt;   260 | 
#&gt;   262 | 
#&gt;   264 | 
#&gt;   266 | 
#&gt;   268 | 
#&gt;   270 | 
#&gt;   272 | 
#&gt;   274 | 
#&gt;   276 | 
#&gt;   278 | 
#&gt;   280 | 
#&gt;   282 | 
#&gt;   284 | 
#&gt;   286 | 
#&gt;   288 | 
#&gt;   290 | 
#&gt;   292 | 
#&gt;   294 | 
#&gt;   296 | 
#&gt;   298 | 
#&gt;   300 | 
#&gt;   302 | 
#&gt;   304 | 
#&gt;   306 | 
#&gt;   308 | 
#&gt;   310 | 
#&gt;   312 | 
#&gt;   314 | 
#&gt;   316 | 
#&gt;   318 | 
#&gt;   320 | 
#&gt;   322 | 
#&gt;   324 | 
#&gt;   326 | 
#&gt;   328 | 
#&gt;   330 | 
#&gt;   332 | 
#&gt;   334 | 
#&gt;   336 | 
#&gt;   338 | 
#&gt;   340 | 
#&gt;   342 | 
#&gt;   344 | 
#&gt;   346 | 
#&gt;   348 | 
#&gt;   350 | 0
#&gt;   352 | 
#&gt;   354 | 
#&gt;   356 | 
#&gt;   358 | 
#&gt;   360 | 
#&gt;   362 | 
#&gt;   364 | 
#&gt;   366 | 
#&gt;   368 | 
#&gt;   370 | 0
#&gt;   372 | 
#&gt;   374 | 
#&gt;   376 | 
#&gt;   378 | 
#&gt;   380 | 
#&gt;   382 | 
#&gt;   384 | 
#&gt;   386 | 
#&gt;   388 | 
#&gt;   390 | 
#&gt;   392 | 
#&gt;   394 | 
#&gt;   396 | 
#&gt;   398 | 
#&gt;   400 | 
#&gt;   402 | 
#&gt;   404 | 
#&gt;   406 | 
#&gt;   408 | 
#&gt;   410 | 
#&gt;   412 | 
#&gt;   414 | 
#&gt;   416 | 
#&gt;   418 | 
#&gt;   420 | 
#&gt;   422 | 
#&gt;   424 | 
#&gt;   426 | 
#&gt;   428 | 
#&gt;   430 | 
#&gt;   432 | 
#&gt;   434 | 
#&gt;   436 | 
#&gt;   438 | 
#&gt;   440 | 
#&gt;   442 | 
#&gt;   444 | 
#&gt;   446 | 
#&gt;   448 | 
#&gt;   450 | 
#&gt;   452 | 
#&gt;   454 | 
#&gt;   456 | 
#&gt;   458 | 
#&gt;   460 | 
#&gt;   462 | 
#&gt;   464 | 
#&gt;   466 | 
#&gt;   468 | 
#&gt;   470 | 
#&gt;   472 | 
#&gt;   474 | 
#&gt;   476 | 
#&gt;   478 | 
#&gt;   480 | 
#&gt;   482 | 
#&gt;   484 | 
#&gt;   486 | 
#&gt;   488 | 
#&gt;   490 | 
#&gt;   492 | 
#&gt;   494 | 
#&gt;   496 | 
#&gt;   498 | 
#&gt;   500 | 0
#&gt; [1] -0.5968958</code></pre>
</div>
</div>
<div id="conclusion" class="section level1">
<h1 class="hasAnchor">
<a href="#conclusion" class="anchor"></a>Conclusion</h1>
<p>The model is able to recover data generating parameters from simulated data and is safe to use in interpretting the data provided by the study participants.</p>
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h1>
<div id="refs" class="references">
<div id="ref-ahn2017">
<p>Ahn, W.-Y., Haines, N., &amp; Zhang, L. (2017). Revealing Neurocomputational Mechanisms of Reinforcement Learning and Decision-Making With the hBayesDM Package. <em>Computational Psychiatry</em>, <em>1</em>, 24–57. doi:<a href="https://doi.org/10.1162/CPSY_a_00002">10.1162/CPSY_a_00002</a></p>
</div>
<div id="ref-guitart-masip2012">
<p>Guitart-Masip, M., Huys, Q. J., Fuentemilla, L., Dayan, P., Duzel, E., &amp; Dolan, R. J. (2012). Go and no-go learning in reward and punishment: Interactions between affect and effect. <em>NeuroImage</em>, <em>62</em>(1), 154–166. doi:<a href="https://doi.org/10.1016/j.neuroimage.2012.04.024">10.1016/j.neuroimage.2012.04.024</a></p>
</div>
<div id="ref-standevelopmentteam2018">
<p>Stan Development Team. (2018). RStan: The R interface to Stan. Retrieved from <a href="http://mc-stan.org/" class="uri">http://mc-stan.org/</a></p>
</div>
</div>
</div>
<div class="footnotes">
<hr>
<ol>
<li id="fn1"><p>Note that these are the <em>raw</em> parameter values which are transformed such that <span class="math inline">\(\epsilon^\prime \in [0,1]\)</span> and <span class="math inline">\(\rho^\prime \in [0,\infty)\)</span>. Similar to logistic regression, estimating the parameters on a scale the is not resticted improves estimation.<a href="#fnref1">↩</a></p></li>
</ol>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#a-model-for-reinforcement-learning">A model for reinforcement learning</a></li>
      <li>
<a href="#reinforcement-learning-model-for-the-splt">Reinforcement learning model for the SPLT</a><ul class="nav nav-pills nav-stacked">
<li><a href="#hierarchical-parameters">Hierarchical Parameters</a></li>
      </ul>
</li>
      <li><a href="#simulating-data">Simulating data</a></li>
      <li>
<a href="#recovery-of-population-parameters">Recovery of population parameters</a><ul class="nav nav-pills nav-stacked">
<li><a href="#simulating-more-iterations">Simulating more iterations</a></li>
      </ul>
</li>
      <li><a href="#conclusion">Conclusion</a></li>
      <li><a href="#references">References</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by John Flournoy.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://pkgdown.r-lib.org/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  

  </body>
</html>
